# To change this template, choose Tools | Templates
# and open the template in the editor.

lCodigo.text=ID:
btnNovo.text=Novo
btnPesquisar.text=Pesquisar
btnSalvar.text=Salvar
btnCancelar.text=Cancelar
btnExcluir.text=Excluir
jaexiste.processo=J\u00E1 existe outro cadastro com numero %s e vara %s, altere-o.
altera.sucesso=Alterado com sucesso
altera.erro=Erro na altera\u00E7\u00E3o
altera.errobusca=No foi poss\u00EDvel localizar registro %s no cadastro
cadastro.sucesso=Cadastrado com sucesso \n id: %s
cadastro.erro=Erro no cadastramento
exclui.confirmacao=Confirma exclus\u00E3o?
exclui.confirmacao.titulo=Confirma?
exclui.ok=Exclu\u00EDdo
exclui.naopode=Cadastro n\u00E3o pode ser exclu\u00EDdo.
Form.title=Dados de Processos
jpDados.TabConstraints.tabTitle=Dados
lNumProcesso.text=N\u00FAmero Processo
lVara.text=Vara
txtIdVara.text=
txtVaraNome.text=
btnPesqVara.text=Pesq. Vara
cbTrt.text=TRT
jLabel3.text=Advogado:
jLabel4.text=Posi\u00E7\u00E3o:
txtIdAdvogado.text=
txtNomeAdvogado.text=
btnPesqAdvogado.text=Pesq. Advogado
rbAutor.text=Autor
rbReu.text=R\u00E9u
jPanel1.border.title=Cliente
jPanel2.border.title=Parte Contr\u00E1ria
jpDetalhes.TabConstraints.tabTitle=Detalhes
jLabel1.text=Advogado Contr\u00E1ria:
txtAdvogadoContraria.text=
jPanel3.border.title=Loca\u00E7\u00E3o
jLabel2.text=Arm\u00E1rio:
jLabel5.text=Gaveta:
txtArmario.text=
txtGaveta.text=
jLabel6.text=N\u00FAmero Recurso:
txtRecurso.text=
jPanel4.border.title=Observa\u00E7\u00E3o
btnPesquisaCliente.text=Pesquisar
btnClienteCadastrar.text=Cadastrar
rbClienteFisica.text=P.F.
rbClienteJuridica.text=P.J
btnPesquisaContraria.text=Pesquisar
btnContrariaCadastrar.text=Cadastrar
rbContrariaFisica.text=P.F
rbContrariaJuridica.text=P.J.
vara.errobusca=No foi poss\u00EDvel localizar vara %s no cadastro
advogado.errobusca=No foi poss\u00EDvel localizar advogado %s no cadastro
pessoa.errobusca=No foi poss\u00EDvel localizar pessoa %s no cadastro
advogado.informe=Informe advogado
cliente.informe=Informe cliente
contraria.informe=Informe contr\u00E1ria
vara.informe=Informe a vara
numeroProcesso.informe=Informe n\u00FAmero do processo
PesquisarCliente.Action.shortDescription=

PesquisarCliente.Action.text=Pesquisar
PesquisarContraria.Action.shortDescription=
PesquisarContraria.Action.text=Pesquisar
PesquisarVara.Action.shortDescription=
PesquisarVara.Action.text=Pesq. Vara
PesquisarAdvogado.Action.shortDescription=
PesquisarAdvogado.Action.text=Pesq. Advogado
CadastrarCliente.Action.text=Cadastrar
CadastrarCliente.Action.shortDescription=
CadastrarContraria.Action.shortDescription=
CadastrarContraria.Action.text=Cadastrar
cbPagaTaxa.text=Paga Taxa
txtValorTaxa.text=
