jaexiste.cpf=J\u00E1 existe outro cadastro com o cpf %s
invalido.cpf=O Cpf %s \u00E9 inv\u00E1lido.
invalido.email=O Email %s \u00E9 inv\u00E1lido.
invalido.dataNascimento=Data de dascimento inv\u00E1lida.
invalido.nome=Informe um nome.


altera.sucesso=Alterado com sucesso
altera.erro=Erro na altera\u00E7\u00E3o
altera.errobusca=No foi possivel localizar registro %s no cadastro
cadastro.sucesso=Cadastrado com sucesso \n id: %s
cadastro.erro=Erro no cadastramento
exclui.confirmacao=Confirma exclus\u00E3o?
exclui.confirmacao.titulo=Confirma?
exclui.ok=Exclu\u00EDdo
exclui.naopode=Cadastro n\u00E3o pode ser exclu\u00EDdo.
Novo.Action.shortDescription=

Novo.Action.text=Novo
Pesquisar.Action.shortDescription=
Pesquisar.Action.text=Pesquisar
Salvar.Action.shortDescription=
Salvar.Action.text=Salvar
Cancelar.Action.shortDescription=
Cancelar.Action.text=Cancelar
Excluir.Action.shortDescription=
Excluir.Action.text=Excluir
jLabel25.text=Fone 3
jLabel26.text=Contato 3
jLabel23.text=Fone 2
jLabel24.text=Contato 2
jLabel27.text=Email
lOE.text=Org\u00E3o Expeditor
lRG.text=RG
lCPF.text=CPF
tabDocumentos.TabConstraints.tabTitle=Documentos
jLabel22.text=Contato 1
jLabel21.text=Fone 1
tabContatos.TabConstraints.tabTitle=Contatos
rbFeminino.text=Feminino
tabObservacao.TabConstraints.tabTitle=Observa\u00E7\u00E3o
rbMasculino.text=Masculino
jLabel13.text=Nome do Pai
jLabel12.text=Nome da M\u00E3e
jLabel15.text=Naturalidade
jLabel14.text=Nacionalidade
jLabel5.text=Profiss\u00E3o
jLabel7.text=Sexo
jLabel6.text=Data de Nascimento
txtCpf.text=
lCTSerie.text=Serie
tabEndereco.TabConstraints.tabTitle=Endere\u00E7o
jLabel4.text=Estado Civil
tabDados.TabConstraints.tabTitle=Dados
jLabel2.text=Nome
lCT.text=Carteira de Trabalho
jLabel1.text=Codigo
Form.title=Cadastro de Pessoa F\u00EDsica
txtCep.text=
jLabel18.text=Cidade
jLabel19.text=UF
jLabel20.text=Bairro
jLabel17.text=CEP
jLabel16.text=Endere\u00E7o
