lCodigo.text=Codigo
lDescricao.text=Nome:
btnSalvar.text=Salvar
btnCancelar.text=Cancelar
btnNovo.text=Novo
Salvar.Action.shortDescription=Salva Cadastro Atual
Salvar.Action.text=Salvar
Novo.Action.shortDescription=
Novo.Action.text=Novo
altera.sucesso=Alterado com sucesso
altera.erro=Erro na altera\u00E7\u00E3o
altera.errobusca=No foi possivel localizar registro %s no cadastro
cadastro.sucesso=Cadastrado com sucesso \n id: %s
cadastro.erro=Erro no cadastramento
jaexiste.nome=J\u00E1 existe outro cadastro com nome %s, altere.
cbDesabilitado.text=desabilitado
btnExcluir.text=Excluir
Excluir.Action.shortDescription=Exclui somente cadastros n\u00E3o utilizados.
Excluir.Action.text=Excluir
Cancelar.Action.shortDescription=Cancela edi\u00E7\u00E3o atual
Cancelar.Action.text=Cancelar
btnPesquisar.text=Pesquisar
Pesquisar.Action.text=Pesquisar
Pesquisar.Action.shortDescription=Abre tela de pesquisa
txtId.text=
txtId.toolTipText=Pressione F10 para pesquisar
exclui.confirmacao=Confirma exclus\u00E3o?
exclui.confirmacao.titulo=Confirma?
exclui.ok=Exclu\u00EDdo
exclui.naopode=Cadastro n\u00E3o pode ser exclu\u00EDdo.
Form.title=Cadastro Comarca
txtNome.text=
