txtId.text=
txtNome.text=
jLabel1.text=Codigo
jLabel2.text=Nome
tabDados.TabConstraints.tabTitle=Dados
tabEndereco.TabConstraints.tabTitle=Endere\u00E7o
tabContatos.TabConstraints.tabTitle=Contatos
tabDocumentos.TabConstraints.tabTitle=Documentos
jLabel4.text=Estado Civil
jLabel5.text=Profiss\u00E3o
jLabel6.text=Data de Nascimento
jLabel7.text=Sexo
jLabel12.text=Nome da M\u00E3e
jLabel13.text=Nome do Pai
jLabel14.text=Nacionalidade
jLabel15.text=Naturalidade
jLabel16.text=Endere\u00E7o
jLabel17.text=CEP
jLabel18.text=Cidade
jLabel19.text=UF
jLabel20.text=Bairro
jLabel21.text=Fone 1
jLabel22.text=Contato 1
jLabel23.text=Fone 2
jLabel24.text=Contato 2
jLabel25.text=Fone 3
jLabel26.text=Contato 3
jLabel27.text=Email
rbMasculino.text=Masculino
rbFeminino.text=Feminino
tabObservacao.TabConstraints.tabTitle=Observa\u00E7\u00E3o
lCPF.text=CPF
lRG.text=RG
lOE.text=Org\u00E3o Expeditor
lCT.text=Carteira de Trabalho
lCTSerie.text=Serie
lOAB.text=OAB
lOABUF.text=UF
txtRG.text=
txtOE.text=
txtCT.text=
txtCTSerie.text=
txtOAB.text=
txtEndereco.text=
txtBairro.text=
txtCidade.text=
btnSalvar.text=Salvar
btnCancelar.text=Cancelar
txtFone1.text=
txtContato1.text=
txtFone2.text=
txtContato2.text=
txtFone3.text=
txtContato3.text=
txtEmail.text=
txtProfissao.text=Advogado
txtNomeMae.text=
txtNomePai.text=
txtNacionalidade.text=
txtNaturalidade.text=
btnNovo.text=Novo
btnPesquisar.text=Pesquisar
Form.title=Cadastro de Advogados
txtCpf.text=
txtCep.text=
btnExcluir.text=Excluir
jaexiste.cpf=J\u00E1 existe outro cadastro com o cpf %s
invalido.cpf=O Cpf %s \u00E9 inv\u00E1lido.
invalido.email=O Email %s \u00E9 inv\u00E1lido.
invalido.dataNascimento=Data de dascimento inv\u00E1lida.
invalido.nome=Informe um nome.


altera.sucesso=Alterado com sucesso
altera.erro=Erro na altera\u00E7\u00E3o
altera.errobusca=No foi possivel localizar registro %s no cadastro
cadastro.sucesso=Cadastrado com sucesso \n id: %s
cadastro.erro=Erro no cadastramento
exclui.confirmacao=Confirma exclus\u00E3o?
exclui.confirmacao.titulo=Confirma?
exclui.ok=Exclu\u00EDdo
exclui.naopode=Cadastro n\u00E3o pode ser exclu\u00EDdo.
Novo.Action.shortDescription=

Novo.Action.text=Novo
Pesquisar.Action.shortDescription=
Pesquisar.Action.text=Pesquisar
Salvar.Action.shortDescription=
Salvar.Action.text=Salvar
Cancelar.Action.shortDescription=
Cancelar.Action.text=Cancelar
Excluir.Action.shortDescription=
Excluir.Action.text=Excluir
