jaexiste.cnpj=J\u00E1 existe outro cadastro com o cnpj %s
invalido.cnpj=O Cnpj %s \u00E9 inv\u00E1lido.
invalido.email=O Email %s \u00E9 inv\u00E1lido.
invalido.nome=Informe um nome.


altera.sucesso=Alterado com sucesso
altera.erro=Erro na altera\u00E7\u00E3o
altera.errobusca=No foi possivel localizar registro %s no cadastro
cadastro.sucesso=Cadastrado com sucesso \n id: %s
cadastro.erro=Erro no cadastramento
exclui.confirmacao=Confirma exclus\u00E3o?
exclui.confirmacao.titulo=Confirma?
exclui.ok=Exclu\u00EDdo
exclui.naopode=Cadastro n\u00E3o pode ser exclu\u00EDdo.
Novo.Action.shortDescription=

Novo.Action.text=Novo
Pesquisar.Action.shortDescription=
Pesquisar.Action.text=Pesquisar
Salvar.Action.shortDescription=
Salvar.Action.text=Salvar
Cancelar.Action.shortDescription=
Cancelar.Action.text=Cancelar
Excluir.Action.shortDescription=
Excluir.Action.text=Excluir
jLabel4.text=C\u00F3digo de Empresa:
lIE.text=Insc. Estadual
lIM.text=Insc. Municipal
tabDocumentos.TabConstraints.tabTitle=Documentos
lCNPJ.text=CNPJ
txtCnpj.text=
tabEndereco.TabConstraints.tabTitle=Endere\u00E7o
jLabel16.text=Endere\u00E7o
jLabel17.text=CEP
jLabel18.text=Cidade
jLabel19.text=UF
jLabel20.text=Bairro
tabContatos.TabConstraints.tabTitle=Contatos
jLabel21.text=Fone 1
txtCep.text=
jLabel24.text=Contato 2
jLabel25.text=Fone 3
jLabel22.text=Contato 1
jLabel23.text=Fone 2
tabDados.TabConstraints.tabTitle=Dados
jLabel3.text=S\u00F3cios:
jLabel26.text=Contato 3
jLabel27.text=Email
jLabel2.text=Nome
jLabel1.text=Codigo
Form.title=Cadastro de Pessoa Jur\u00EDdica
tabObservacao.TabConstraints.tabTitle=Observa\u00E7\u00E3o
