# To change this template, choose Tools | Templates
# and open the template in the editor.

lCodigo.text=ID:
btnNovo.text=Novo
btnPesquisar.text=Pesquisar
btnSalvar.text=Salvar
btnCancelar.text=Cancelar
btnExcluir.text=Excluir
jaexiste.processo=J\u00E1 existe outro cadastro com numero %s e vara %s, altere-o.
altera.sucesso=Alterado com sucesso
altera.erro=Erro na altera\u00E7\u00E3o
altera.errobusca=No foi poss\u00EDvel localizar registro %s no cadastro
cadastro.sucesso=Cadastrado com sucesso \n id: %s
cadastro.erro=Erro no cadastramento
exclui.confirmacao=Confirma exclus\u00E3o?
exclui.confirmacao.titulo=Confirma?
exclui.ok=Exclu\u00EDdo
exclui.naopode=Cadastro n\u00E3o pode ser exclu\u00EDdo.
Form.title=Andamento de Processos
jpDados.TabConstraints.tabTitle=Dados do Processo
lNumProcesso.text=N\u00FAmero Processo
lVara.text=Vara
txtIdVara.text=
txtVaraNome.text=
btnPesqVara.text=Pesq. Vara
jLabel3.text=Advogado:
jLabel4.text=Posi\u00E7\u00E3o:
txtIdAdvogado.text=
txtNomeAdvogado.text=
jPanel2.border.title=Parte Contr\u00E1ria
jpDetalhes.TabConstraints.tabTitle=Andamentos
jLabel1.text=Advogado:
txtAdvogadoContraria.text=
processo.errobusca=No foi poss\u00EDvel localizar processo %s no cadastro
vara.errobusca=No foi poss\u00EDvel localizar vara %s no cadastro
advogado.errobusca=No foi poss\u00EDvel localizar advogado %s no cadastro
pessoa.errobusca=No foi poss\u00EDvel localizar pessoa %s no cadastro
advogado.informe=Informe advogado
cliente.informe=Informe cliente
contraria.informe=Informe contr\u00E1ria
vara.informe=Informe a vara
numeroProcesso.informe=Informe n\u00FAmero do processo
PesquisarCliente.Action.shortDescription=

PesquisarCliente.Action.text=Pesquisar
PesquisarContraria.Action.shortDescription=
PesquisarContraria.Action.text=Pesquisar
PesquisarVara.Action.shortDescription=
PesquisarVara.Action.text=Pesq. Vara
PesquisarAdvogado.Action.shortDescription=
PesquisarAdvogado.Action.text=Pesq. Advogado
jLabel2.text=Cliente:
jPanel1.TabConstraints.tabTitle=Dados Acompanhamento
jTabbedPane2.AccessibleContext.accessibleName=andamento
jPanel3.border.title=Hist\u00F3rico
jLabel5.text=Data Cadastro:
jLabel6.text=Data Provid\u00EAncia:
jLabel7.text=Hora Provid\u00EAncia:
cbBaixa.text=Baixa
jLabel8.text=Data Baixa:
txtHoraProvidencia.text=
jPanel4.TabConstraints.tabTitle=Acordo Parcelamento
jLabel9.text=Valor:
jFormattedTextField1.text=jFormattedTextField1
jFormattedTextField2.text=jFormattedTextField2
jLabel10.text=Vencimento:
btnIncluirParcela.text=Incluir Parcela
jPanel5.border.title=Observa\u00E7\u00E3o
jPanel6.border.title=Tipo Andamento
jPanel7.AccessibleContext.accessibleName=Tipo Audi\u00EAncia
jPanel7.border.title=Tipo Audi\u00EAncia
btnMudarProcesso.text=jButton1
OutroProcesso.Action.shortDescription=
OutroProcesso.Action.text=Mudar Processo
