# To change this template, choose Tools | Templates
# and open the template in the editor.

lCodigo.text=ID:
lNome.text=Nome:
btnNovo.text=Novo
btnPesquisar.text=Pesquisar
btnSalvar.text=Salvar
btnCancelar.text=Cancelar
btnExcluir.text=Excluir
cbDesabilitado.text=Desabilitado
lApelido.text=Apelido:
txtNome.text=
txtSenha.text=
jLabel1.text=Senha:
cbAdministrador.text=Administrador
jLabel2.text=Email:
txtEmail.text=
jaexiste.apelido=J\u00E1 existe outro cadastro com apelido %s, altere.
altera.sucesso=Alterado com sucesso
altera.erro=Erro na altera\u00E7\u00E3o
altera.errobusca=No foi possivel localizar registro %s no cadastro
cadastro.sucesso=Cadastrado com sucesso \n id: %s
cadastro.erro=Erro no cadastramento
exclui.confirmacao=Confirma exclus\u00E3o?
exclui.confirmacao.titulo=Confirma?
exclui.ok=Exclu\u00EDdo
exclui.naopode=Cadastro n\u00E3o pode ser exclu\u00EDdo.
Form.title=Cadastro de Usu\u00E1rio
btnAddHab.text=Adicionar
btnRemHab.text=Remover Selecionado
jpHab.TabConstraints.tabTitle=Habilita\u00E7\u00F5es
jpDados.TabConstraints.tabTitle=Dados
