jLabel1.text=Importador de dados Dados do Sistema Atdb
btnIniciar.text=Iniciar Importa\u00E7\u00E3o
jLabel2.text=Arquivo deve estar em c:\\atdb\\dados\\atbd.gdb
jLabel3.text=\u00C9 recomendavel rodar o schedula no prompt de comando com: java -jar schedula.jar
