jLabel1.text=Data Inicial
jLabel2.text=Data Final
jLabel3.text=Pauta Di\u00E1ria
#NOI18N
jLabel3.font=DejaVu LGC Sans-Plain-18
jLabel4.text=Selecione o Per\u00EDodo de Emiss\u00E3o
btnEmitir.text=Emitir
Form.title=Pauta Di\u00E1ria
