# Application global resources

Application.name = schedula
Application.title = Controle de Agendamentos para Advocacia
Application.version = 1.0
Application.vendor = Peretti Assessoria e Sistemas Ltda.
Application.homepage = http://www.perettis.com.br/
Application.description = Sistema de get\u00E3o de agenda de escrit\u00F3rios de \nadvocacia.
Application.vendorId = Peretti Assessoria e Sistemas LTDA
Application.id = schedula
Application.lookAndFeel = system
quit.Action.shortDescription=
quit.Action.text=Sair
