jLabel1.text=Conex\u00E3o:
jLabel2.text=Dialeto:
jLabel3.text=Driver:
jLabel4.text=Usu\u00E1rio:
jLabel5.text=Senha:
jPanel1.TabConstraints.tabTitle=Banco de Dados
jLabel6.text=Configura\u00E7\u00E3o do Sistema
jbSalvar.text=Salvar
jbCancelar.text=Sair
txtConexao.text=
txtDialeto.text=
txtDriver.text=
txtUsuario.text=
txtSenha.text=
saveConfig.Action.shortDescription=
saveConfig.Action.text=Salvar
jPanel2.TabConstraints.tabTitle=Dados da Empresa
jLabel7.text=Nome
txtNomeEmpresa.text=
