helpMenu.text = Ajuda
showAboutBox.Action.text = Sobre...
showAboutBox.Action.shortDescription = Mostra informa\u00E7\u00F5es sobre a aplica\u00E7\u00E3o

# status bar resources

StatusBar.messageTimeout = 5000
StatusBar.busyAnimationRate = 30
StatusBar.idleIcon = busyicons/idle-icon.png
StatusBar.busyIcons[0]  = busyicons/busy-icon0.png
StatusBar.busyIcons[1]  = busyicons/busy-icon1.png
StatusBar.busyIcons[2]  = busyicons/busy-icon2.png
StatusBar.busyIcons[3]  = busyicons/busy-icon3.png
StatusBar.busyIcons[4]  = busyicons/busy-icon4.png
StatusBar.busyIcons[5]  = busyicons/busy-icon5.png
StatusBar.busyIcons[6]  = busyicons/busy-icon6.png
StatusBar.busyIcons[7]  = busyicons/busy-icon7.png
StatusBar.busyIcons[8]  = busyicons/busy-icon8.png
StatusBar.busyIcons[9]  = busyicons/busy-icon9.png
StatusBar.busyIcons[10] = busyicons/busy-icon10.png
StatusBar.busyIcons[11] = busyicons/busy-icon11.png
StatusBar.busyIcons[12] = busyicons/busy-icon12.png
StatusBar.busyIcons[13] = busyicons/busy-icon13.png
StatusBar.busyIcons[14] = busyicons/busy-icon14.png
CadastrosMenu.text=Cadastros
advogadosItem.text=Advogados
cadastroAdvogados.Action.shortDescription=Cadastro de Advogados
cadastroAdvogados.Action.text=Advogados
jMenu1.text=Parametros
cadastroEstadoCivil.Action.text=Estado Civil
cadastroEstadoCivil.Action.shortDescription=Cadastro de Tipos de Estado Civil
pessoaFisicaItem.text=Pessoa F\u00EDsica
pessoaJuridicaItem.text=Pessoa Jur\u00EDdica
processosItem.text=Dados de Processos
acompanhamentosItem.text=Acompanhamentos
opcoesSchedulaItem.text=Op\u00E7\u00F5es Schedula
tipoAudienciaItem.text=Tipo de Audi\u00EAncia
comarcaItem.text=Comarca
varaItem.text=Vara
processosMenu.text=Processos
jMenu2.text=Arquivo
exitMenuItem.text=Sair
jMenu3.text=Relat\u00F3rios
diarioItem.text=Di\u00E1rio
estadoCivilItem.text=Estado Civil
gestaoUsuariosMenu.text=Gest\u00E3o Usu\u00E1rios
usuariosItem.text=Usu\u00E1rios
trocaSenhaItem.text=Trocar Senha
informacoesUser.text=Informa\u00E7\u00F5es de Autentica\u00E7\u00E3o
cadastroUsuario.Action.shortDescription=Cadastro de usu\u00E1rios do sistema.
cadastroUsuario.Action.text=Usu\u00E1rios
jmiConfiguracoes.text=Item
schedulaConfig.Action.shortDescription=
schedulaConfig.Action.text=Configura\u00E7\u00F5es
cadastroComarca.Action.shortDescription=
cadastroComarca.Action.text=Comarca
comarcaItem.toolTipText=
cadastroVara.Action.shortDescription=
cadastroVara.Action.text=Vara
cadastroAudienciaTipo.Action.shortDescription=
cadastroAudienciaTipo.Action.text=Tipo de Audi\u00EAncia
cadastroPessoaFisica.Action.shortDescription=
cadastroPessoaFisica.Action.text=Pessoa F\u00EDsica
cadastroPessoaJuridica.Action.shortDescription=
cadastroPessoaJuridica.Action.text=Pessoa Jur\u00EDdica
cadastroProcesso.Action.text=Dados de Processos
cadastroProcesso.Action.shortDescription=
cadastroAndamentoProcesso.Action.shortDescription=
cadastroAndamentoProcesso.Action.text=Andamento
jMenuItem1.text=Implantar
doAtdb.Action.shortDescription=
doAtdb.Action.text=Sistema Atdb
relatorioPautaDiaria.Action.shortDescription=
relatorioPautaDiaria.Action.text=Pauta Di\u00E1ria
relatorioPautaDiaria.Action.accelerator=alt pressed D
schedulaOpcoes.Action.text=Op\u00E7\u00F5es Schedula
schedulaOpcoes.Action.shortDescription=
trocaSenha.Action.shortDescription=
trocaSenha.Action.text=Trocar Senha
imagem.text=
#NOI18N
imagem.icon=SCHEDULA.png
cadastroProcesso.Action.accelerator=alt pressed P
cadastroAndamentoProcesso.Action.accelerator=alt pressed A
cadastroPessoaFisica.Action.accelerator=alt pressed F
cadastroPessoaJuridica.Action.accelerator=alt pressed J
jMenu4.text=Importa\u00E7\u00E3o
