title = Sobre: ${Application.title} ${Application.version} 

closeAboutBox.Action.text = &Fechar
appDescLabel.text=<html>${Application.description}
homepageLabel.text=P\u00E1gina na Internet:
versionLabel.text=Vers\u00E3o do Produto:
vendorLabel.text=Fabricante:
