# Application global resources

Application.name = schedula
Application.title = Controle de Agendamentos para Advocacia
Application.version = 1.0
Application.vendor = Peretti
Application.homepage = https://www.peretti.eti.br/
Application.description = Sistema de get\u00E3o de agenda de escrit\u00F3rios de \nadvocacia.
Application.vendorId = Peretti
Application.id = schedula
Application.lookAndFeel = system
quit.Action.shortDescription=
quit.Action.text=Sair
