jLabel1.text=Definir Nova Senha
#NOI18N
jLabel1.font=DejaVu LGC Sans-Bold-18
jLabel2.text=Usu\u00E1rio:
lblUsuario.text=
jLabel3.text=Senha Atual:
jLabel4.text=Nova Senha:
jLabel5.text=Confirmar Nova Senha:
txtSenhaAtual.text=
txtNovaSenha.text=
txtConfirmaNovaSenha.text=
btnConfirmar.text=Confirmar
btnCancelar.text=Cancelar
