/*
 * CadastroEstadoCivil.java
 *
 * Created on May 27, 2008, 9:09 PM
 */
package br.com.perettis.schedula;

import br.com.perettis.gets.dao.DAOConstants;
import br.com.perettis.gets.swing.FormSearch;
import br.com.perettis.gets.swing.NumericDocument;
import br.com.perettis.gets.swing.GetsDocument;
import br.com.perettis.gets.dao.DAOFactoryAbstract;
import br.com.perettis.gets.swing.FormSearchColumn;
import br.com.perettis.gets.text.BooleanFormat;
import br.com.perettis.schedula.entity.Advogado;
import br.com.perettis.schedula.entity.Pessoa;
import br.com.perettis.schedula.entity.PessoaFisica;
import br.com.perettis.schedula.entity.PessoaJuridica;
import br.com.perettis.schedula.entity.SchedulaRotina;
import br.com.perettis.schedula.entity.Processo;
import br.com.perettis.schedula.entity.Vara;
import br.com.perettis.schedula.model.AdvogadoDAO;
import br.com.perettis.schedula.model.PessoaDAO;
import br.com.perettis.schedula.model.PessoaJuridicaDAO;
import br.com.perettis.schedula.model.PessoaFisicaDAO;
import br.com.perettis.schedula.model.SchedulaDAOFactory;
import br.com.perettis.schedula.model.SchedulaRotinaDAO;
import br.com.perettis.schedula.model.Seguranca;
import br.com.perettis.schedula.model.ProcessoDAO;
import br.com.perettis.schedula.model.VaraDAO;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import org.hibernate.Transaction;
import org.jdesktop.application.Action;

/**
 *
 * @author  Vinicius Peretti
 * 
 * 
 */
public class CadastroProcesso extends javax.swing.JFrame {

    Processo processo;
    ProcessoDAO processoDAO;
    private SchedulaDAOFactory daoFactory;
    Transaction t;
    org.jdesktop.application.ResourceMap resourceMap;
    FormSearch<Long, Processo, ProcessoDAO> pesquisa;
    FormSearch<Integer, Vara, VaraDAO> pesquisaVara;
    FormSearch<Long, Advogado, AdvogadoDAO> pesquisaAdvogado;
    FormSearch<Long, PessoaFisica, PessoaFisicaDAO> pesquisaPessoaFisica;
    FormSearch<Long, PessoaJuridica, PessoaJuridicaDAO> pesquisaPessoaJuridica;
    NumberFormat formataDouble = NumberFormat.getInstance(new Locale("pt", "BR"));
    Vara vara;
    Advogado advogado;
    Pessoa cliente;
    Pessoa contraria;
    
    /** Creates new form CadastroEstadoCivil */
    public CadastroProcesso(SchedulaDAOFactory daoFactory) {
        setDaoFactory(daoFactory);
        initComponents();
        ResetaForm();
        resourceMap = org.jdesktop.application.Application.getInstance(
                br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroProcesso.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alerta = new javax.swing.JOptionPane();
        bgPosicao = new javax.swing.ButtonGroup();
        bgCliente = new javax.swing.ButtonGroup();
        bgParteContraria = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpDados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbAutor = new javax.swing.JRadioButton();
        rbReu = new javax.swing.JRadioButton();
        txtIdAdvogado = new javax.swing.JTextField();
        txtNomeAdvogado = new javax.swing.JTextField();
        btnPesqAdvogado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnPesquisaCliente = new javax.swing.JButton();
        txtNomeCliente = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        btnClienteCadastrar = new javax.swing.JButton();
        rbClienteFisica = new javax.swing.JRadioButton();
        rbClienteJuridica = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnPesquisaContraria = new javax.swing.JButton();
        txtNomeContraria = new javax.swing.JTextField();
        txtIdContraria = new javax.swing.JTextField();
        btnContrariaCadastrar = new javax.swing.JButton();
        rbContrariaFisica = new javax.swing.JRadioButton();
        rbContrariaJuridica = new javax.swing.JRadioButton();
        txtAdvogadoContraria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbTrt = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtArmario = new javax.swing.JTextField();
        txtGaveta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRecurso = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        cbPagaTaxa = new javax.swing.JCheckBox();
        txtValorTaxa = new javax.swing.JFormattedTextField();
        jpDetalhes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalhes = new javax.swing.JEditorPane();
        btnNovo = new javax.swing.JButton();
        lNumProcesso = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lCodigo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtId = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        txtNumeroProcesso = new javax.swing.JFormattedTextField();
        lVara = new javax.swing.JLabel();
        txtIdVara = new javax.swing.JTextField();
        txtVaraNome = new javax.swing.JTextField();
        btnPesqVara = new javax.swing.JButton();

        alerta.setName("alerta"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroProcesso.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImage(new Imagens().getIcone());
        setName("Form"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jpDados.setName("jpDados"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        bgPosicao.add(rbAutor);
        rbAutor.setText(resourceMap.getString("rbAutor.text")); // NOI18N
        rbAutor.setName("rbAutor"); // NOI18N

        bgPosicao.add(rbReu);
        rbReu.setText(resourceMap.getString("rbReu.text")); // NOI18N
        rbReu.setName("rbReu"); // NOI18N

        txtIdAdvogado.setText(resourceMap.getString("txtIdAdvogado.text")); // NOI18N
        txtIdAdvogado.setName("txtIdAdvogado"); // NOI18N
        txtIdAdvogado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdAdvogadoFocusLost(evt);
            }
        });

        txtNomeAdvogado.setEditable(false);
        txtNomeAdvogado.setText(resourceMap.getString("txtNomeAdvogado.text")); // NOI18N
        txtNomeAdvogado.setName("txtNomeAdvogado"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getActionMap(CadastroProcesso.class, this);
        btnPesqAdvogado.setAction(actionMap.get("PesquisarAdvogado")); // NOI18N
        btnPesqAdvogado.setText(resourceMap.getString("btnPesqAdvogado.text")); // NOI18N
        btnPesqAdvogado.setName("btnPesqAdvogado"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        btnPesquisaCliente.setAction(actionMap.get("PesquisarCliente")); // NOI18N
        btnPesquisaCliente.setText(resourceMap.getString("btnPesquisaCliente.text")); // NOI18N
        btnPesquisaCliente.setName("btnPesquisaCliente"); // NOI18N

        txtNomeCliente.setEditable(false);
        txtNomeCliente.setName("txtNomeCliente"); // NOI18N

        txtIdCliente.setName("txtIdCliente"); // NOI18N
        txtIdCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdClienteFocusLost(evt);
            }
        });

        btnClienteCadastrar.setAction(actionMap.get("CadastrarCliente")); // NOI18N
        btnClienteCadastrar.setText(resourceMap.getString("btnClienteCadastrar.text")); // NOI18N
        btnClienteCadastrar.setName("btnClienteCadastrar"); // NOI18N

        bgCliente.add(rbClienteFisica);
        rbClienteFisica.setText(resourceMap.getString("rbClienteFisica.text")); // NOI18N
        rbClienteFisica.setName("rbClienteFisica"); // NOI18N

        bgCliente.add(rbClienteJuridica);
        rbClienteJuridica.setText(resourceMap.getString("rbClienteJuridica.text")); // NOI18N
        rbClienteJuridica.setName("rbClienteJuridica"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClienteCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbClienteFisica)
                    .addComponent(rbClienteJuridica))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnPesquisaCliente)
                .addComponent(btnClienteCadastrar)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(rbClienteFisica)
                    .addGap(1, 1, 1)
                    .addComponent(rbClienteJuridica)))
        );

        NumericDocument gdIdCliente = new NumericDocument();
        gdIdCliente.setMaxLenght(12);
        txtIdCliente.setDocument(gdIdCliente);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        btnPesquisaContraria.setAction(actionMap.get("PesquisarContraria")); // NOI18N
        btnPesquisaContraria.setText(resourceMap.getString("btnPesquisaContraria.text")); // NOI18N
        btnPesquisaContraria.setName("btnPesquisaContraria"); // NOI18N

        txtNomeContraria.setEditable(false);
        txtNomeContraria.setName("txtNomeContraria"); // NOI18N

        txtIdContraria.setName("txtIdContraria"); // NOI18N
        txtIdContraria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdContrariaFocusLost(evt);
            }
        });

        btnContrariaCadastrar.setAction(actionMap.get("CadastrarContraria")); // NOI18N
        btnContrariaCadastrar.setText(resourceMap.getString("btnContrariaCadastrar.text")); // NOI18N
        btnContrariaCadastrar.setName("btnContrariaCadastrar"); // NOI18N

        bgParteContraria.add(rbContrariaFisica);
        rbContrariaFisica.setText(resourceMap.getString("rbContrariaFisica.text")); // NOI18N
        rbContrariaFisica.setName("rbContrariaFisica"); // NOI18N

        bgParteContraria.add(rbContrariaJuridica);
        rbContrariaJuridica.setText(resourceMap.getString("rbContrariaJuridica.text")); // NOI18N
        rbContrariaJuridica.setName("rbContrariaJuridica"); // NOI18N

        txtAdvogadoContraria.setText(resourceMap.getString("txtAdvogadoContraria.text")); // NOI18N
        txtAdvogadoContraria.setName("txtAdvogadoContraria"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdvogadoContraria))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtIdContraria, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeContraria, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisaContraria, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnContrariaCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbContrariaFisica)
                            .addComponent(rbContrariaJuridica))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtIdContraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeContraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisaContraria)
                            .addComponent(btnContrariaCadastrar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rbContrariaFisica)
                        .addGap(1, 1, 1)
                        .addComponent(rbContrariaJuridica)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAdvogadoContraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        NumericDocument gdIdContraria = new NumericDocument();
        gdIdContraria.setMaxLenght(12);
        txtIdContraria.setDocument(gdIdContraria);
        new GetsDocument().setMaxLenght(100, txtAdvogadoContraria);

        cbTrt.setText(resourceMap.getString("cbTrt.text")); // NOI18N
        cbTrt.setName("cbTrt"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel3.border.title"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        txtArmario.setText(resourceMap.getString("txtArmario.text")); // NOI18N
        txtArmario.setName("txtArmario"); // NOI18N

        txtGaveta.setText(resourceMap.getString("txtGaveta.text")); // NOI18N
        txtGaveta.setName("txtGaveta"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArmario, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGaveta, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(txtGaveta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addComponent(txtArmario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
        );

        new GetsDocument().setMaxLenght(10, txtArmario);
        new GetsDocument().setMaxLenght(10, txtGaveta);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        txtRecurso.setText(resourceMap.getString("txtRecurso.text")); // NOI18N
        txtRecurso.setName("txtRecurso"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        txtObservacao.setName("txtObservacao"); // NOI18N
        jScrollPane2.setViewportView(txtObservacao);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        cbPagaTaxa.setText(resourceMap.getString("cbPagaTaxa.text")); // NOI18N
        cbPagaTaxa.setName("cbPagaTaxa"); // NOI18N
        cbPagaTaxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPagaTaxaActionPerformed(evt);
            }
        });

        txtValorTaxa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtValorTaxa.setText(resourceMap.getString("txtValorTaxa.text")); // NOI18N
        txtValorTaxa.setName("txtValorTaxa"); // NOI18N

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.CENTER, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(38, 38, 38)
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDadosLayout.createSequentialGroup()
                                .addComponent(rbAutor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbReu))
                            .addGroup(jpDadosLayout.createSequentialGroup()
                                .addComponent(txtIdAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesqAdvogado))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDadosLayout.createSequentialGroup()
                                .addComponent(cbTrt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbPagaTaxa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTaxa, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesqAdvogado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbAutor)
                    .addComponent(rbReu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(txtRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(cbPagaTaxa)
                        .addComponent(cbTrt))
                    .addComponent(txtValorTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        NumericDocument gdIdAdvogado = new NumericDocument();
        gdIdAdvogado.setMaxLenght(12);
        txtIdAdvogado.setDocument(gdIdAdvogado);
        new GetsDocument().setMaxLenght(20, txtRecurso);

        jTabbedPane1.addTab(resourceMap.getString("jpDados.TabConstraints.tabTitle"), jpDados); // NOI18N

        jpDetalhes.setName("jpDetalhes"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtDetalhes.setName("txtDetalhes"); // NOI18N
        jScrollPane1.setViewportView(txtDetalhes);

        javax.swing.GroupLayout jpDetalhesLayout = new javax.swing.GroupLayout(jpDetalhes);
        jpDetalhes.setLayout(jpDetalhesLayout);
        jpDetalhesLayout.setHorizontalGroup(
            jpDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetalhesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpDetalhesLayout.setVerticalGroup(
            jpDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetalhesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("jpDetalhes.TabConstraints.tabTitle"), jpDetalhes); // NOI18N

        btnNovo.setAction(actionMap.get("Novo")); // NOI18N
        btnNovo.setText(resourceMap.getString("btnNovo.text")); // NOI18N
        btnNovo.setName("btnNovo"); // NOI18N

        lNumProcesso.setText(resourceMap.getString("lNumProcesso.text")); // NOI18N
        lNumProcesso.setName("lNumProcesso"); // NOI18N

        btnExcluir.setAction(actionMap.get("Excluir")); // NOI18N
        btnExcluir.setText(resourceMap.getString("btnExcluir.text")); // NOI18N
        btnExcluir.setName("btnExcluir"); // NOI18N

        btnCancelar.setAction(actionMap.get("Cancelar")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        lCodigo.setText(resourceMap.getString("lCodigo.text")); // NOI18N
        lCodigo.setName("lCodigo"); // NOI18N

        btnSalvar.setAction(actionMap.get("Salvar")); // NOI18N
        btnSalvar.setText(resourceMap.getString("btnSalvar.text")); // NOI18N
        btnSalvar.setName("btnSalvar"); // NOI18N

        txtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId.setName("txtId"); // NOI18N
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        btnPesquisar.setAction(actionMap.get("Pesquisar")); // NOI18N
        btnPesquisar.setText(resourceMap.getString("btnPesquisar.text")); // NOI18N
        btnPesquisar.setName("btnPesquisar"); // NOI18N

        txtNumeroProcesso.setName("txtNumeroProcesso"); // NOI18N
        txtNumeroProcesso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroProcessoFocusLost(evt);
            }
        });

        lVara.setText(resourceMap.getString("lVara.text")); // NOI18N
        lVara.setName("lVara"); // NOI18N

        txtIdVara.setText(resourceMap.getString("txtIdVara.text")); // NOI18N
        txtIdVara.setName("txtIdVara"); // NOI18N
        txtIdVara.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdVaraFocusLost(evt);
            }
        });

        txtVaraNome.setEditable(false);
        txtVaraNome.setText(resourceMap.getString("txtVaraNome.text")); // NOI18N
        txtVaraNome.setName("txtVaraNome"); // NOI18N

        btnPesqVara.setText(resourceMap.getString("btnPesqVara.text")); // NOI18N
        btnPesqVara.setName("btnPesqVara"); // NOI18N
        btnPesqVara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqVaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lNumProcesso)
                            .addComponent(lCodigo))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumeroProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lVara)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdVara, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVaraNome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesqVara))))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnPesquisar)
                    .addComponent(lCodigo)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumProcesso)
                    .addComponent(txtNumeroProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lVara)
                    .addComponent(txtIdVara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVaraNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesqVara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NumericDocument gdId = new NumericDocument();
        gdId.setMaxLenght(12);
        txtId.setDocument(gdId);
        new GetsDocument().setMaxLenght(20, txtNumeroProcesso);
        NumericDocument gdIdVara = new NumericDocument();
        gdIdVara.setMaxLenght(6);
        txtIdVara.setDocument(gdIdVara);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-721)/2, (screenSize.height-647)/2, 721, 647);
    }// </editor-fold>//GEN-END:initComponents

    
private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
    if (!txtId.getText().equalsIgnoreCase("")) {
        Alterar();
    }
}//GEN-LAST:event_txtIdFocusLost

    @SuppressWarnings("static-access")
private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
}//GEN-LAST:event_txtIdKeyTyped

private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_F10) {
        Pesquisar();
    }
}//GEN-LAST:event_txtIdKeyPressed

private void txtIdVaraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdVaraFocusLost
    VaraCarrega();
    if ((txtIdVara.getText().length() > 0) && (txtNumeroProcesso.getText().length() > 0) && (txtId.isEnabled())) {
        Alterar();
    }
}//GEN-LAST:event_txtIdVaraFocusLost

private void txtIdAdvogadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdAdvogadoFocusLost
    AdvogadoCarrega();
}//GEN-LAST:event_txtIdAdvogadoFocusLost

private void txtIdClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdClienteFocusLost
    ClienteCarrega();
}//GEN-LAST:event_txtIdClienteFocusLost

private void txtIdContrariaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdContrariaFocusLost
    ContrariaCarrega();
}//GEN-LAST:event_txtIdContrariaFocusLost

private void btnPesqVaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqVaraActionPerformed
    PesquisarVara();
    
    if ((txtIdVara.getText().length() > 0) && (txtNumeroProcesso.getText().length() >0) && (txtId.isEnabled())){
        Alterar();
    }
}//GEN-LAST:event_btnPesqVaraActionPerformed

private void txtNumeroProcessoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroProcessoFocusLost
    if ((txtIdVara.getText().length() > 0) && (txtNumeroProcesso.getText().length() >0) && (txtId.isEnabled())){
        Alterar();
    }
}//GEN-LAST:event_txtNumeroProcessoFocusLost

private void cbPagaTaxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPagaTaxaActionPerformed
    PagaTaxa();
}//GEN-LAST:event_cbPagaTaxaActionPerformed



    public void PagaTaxa() {
        txtValorTaxa.setEnabled(cbPagaTaxa.isSelected());
    }
    
    /**
     * Reinicia formulário
     */
  	public void ResetaForm() {
		txtId.setText("");
        txtAdvogadoContraria.setText("");
        txtArmario.setText("");
        txtDetalhes.setText("");
        txtGaveta.setText("");
        txtIdAdvogado.setText("");
        txtIdCliente.setText("");
        txtIdContraria.setText("");
        txtIdVara.setText("");
        txtNomeAdvogado.setText("");
        txtNomeCliente.setText("");
        txtNomeContraria.setText("");
        txtNumeroProcesso.setText("");
        txtObservacao.setText("");
        txtRecurso.setText("");
        txtVaraNome.setText("");
        rbAutor.setSelected(true);
        rbClienteFisica.setSelected(true);
        rbContrariaJuridica.setSelected(true);

        vara = null;
        advogado = null;
        cliente = null;
        contraria = null;

        
        cbTrt.setSelected(false);
		txtId.setEnabled(true);
        
        txtIdVara.setEnabled(true);
        btnPesqVara.setEnabled(true);
        txtNumeroProcesso.setEnabled(true);

		txtId.requestFocus();
		btnSalvar.setEnabled(false);
		btnExcluir.setEnabled(false);
        jTabbedPane1.setSelectedIndex(0);
        
        txtValorTaxa.setText("");
        cbPagaTaxa.setSelected(false);
        PagaTaxa();
        
	}
    
    @Action
    /**
     * Abre tela de pesquisa
     */
    public void Pesquisar(){

        if (pesquisa == null) {
            pesquisa = new PesquisaProcesso(getDaoFactory());
        }
                
        pesquisa.setTitle("Selecione o Processo para Alteração.");
        pesquisa.doSearch();
        pesquisa.openSearch();
        Processo vem = pesquisa.getEntity();
        if (vem != null){
            txtId.setText(String.valueOf(vem.getId()));
            Alterar();
        }
    }

    @Action
    /**
     * Abre tela de pesquisa
     */
    public void PesquisarVara(){

        if (pesquisaVara == null) {
            pesquisaVara = new PesquisaVara(getDaoFactory());
        }
                
        pesquisaVara.setTitle("Selecione a Vara.");
        pesquisaVara.doSearch();
        pesquisaVara.openSearch();
        vara = pesquisaVara.getEntity();
        if (vara != null){
            txtIdVara.setText(String.valueOf(vara.getId()));
            VaraCarrega();
        }
    }

    @Action
    /**
     * Abre tela de pesquisa
     */
    public void PesquisarAdvogado(){

        if (pesquisaAdvogado == null) {
            pesquisaAdvogado = new PesquisaAdvogado(getDaoFactory());
        }
                
        pesquisaAdvogado.setTitle("Selecione o Advogado.");
        pesquisaAdvogado.doSearch();
        pesquisaAdvogado.openSearch();
        advogado = pesquisaAdvogado.getEntity();
        if (advogado != null){
            txtIdAdvogado.setText(String.valueOf(advogado.getId()));
            AdvogadoCarrega();
        }
    }
    
    @Action
    /**
     * Abre tela de pesquisa
     */
    public PessoaFisica PesquisarPessoaFisica(){

        if (pesquisaPessoaFisica == null) {
            pesquisaPessoaFisica = new PesquisaPessoaFisica(getDaoFactory());
        }
                
        pesquisaPessoaFisica.setTitle("Selecione o Pessoa Física.");
        pesquisaPessoaFisica.doSearch();
        pesquisaPessoaFisica.openSearch();
        
        return pesquisaPessoaFisica.getEntity();
    }

    @Action
    /**
     * Abre tela de pesquisa
     */
    public PessoaJuridica PesquisarPessoaJuridica(){

        if (pesquisaPessoaJuridica == null) {
            pesquisaPessoaJuridica = new PesquisaPessoaJuridica(getDaoFactory());
        }
                
        pesquisaPessoaJuridica.setTitle("Selecione o Pessoa Juridica.");
        pesquisaPessoaJuridica.doSearch();
        pesquisaPessoaJuridica.openSearch();
        
        return pesquisaPessoaJuridica.getEntity();
    }

    @Action
    /**
     * Pesquisa cliente
     */
    public void PesquisarCliente(){
        Pessoa vem;
        if (rbClienteFisica.isSelected()){
            vem = (Pessoa) PesquisarPessoaFisica();
        }else{
            vem = (Pessoa) PesquisarPessoaJuridica();
        }
        if (vem != null) {
            txtIdCliente.setText(vem.getId().toString());
            ClienteCarrega();
        }
    }
    
    @Action
    /**
     * Pesquisa contraria
     */
    public void PesquisarContraria(){
        Pessoa vem;
        if (rbContrariaFisica.isSelected()){
            vem = (Pessoa) PesquisarPessoaFisica();
        }else{
            vem = (Pessoa) PesquisarPessoaJuridica();
        }
        if (vem != null) {
            txtIdContraria.setText(vem.getId().toString());
            ContrariaCarrega();
        }
    }
    
    @Action
    /**
     * Cadastra cliente
     */
    public void CadastrarCliente(){
        Pessoa vem;
        if (rbClienteFisica.isSelected()){
            CadastroPessoaFisica cpf = new CadastroPessoaFisica(daoFactory);
            cpf.setModal(true);
            cpf.setVisible(true);
            vem = (Pessoa) cpf.getUltimoCadastro();
        }else{
            CadastroPessoaJuridica cpj = new CadastroPessoaJuridica(daoFactory);
            cpj.setModal(true);
            cpj.setVisible(true);
            vem = (Pessoa) cpj.getUltimoCadastro();
        }
        if (vem != null) {
            txtIdCliente.setText(vem.getId().toString());
            ClienteCarrega();
        }
    }

    @Action
    /**
     * Cadastra contraria
     */
    public void CadastrarContraria(){
        Pessoa vem;
        if (rbContrariaFisica.isSelected()){
            CadastroPessoaFisica cpf = new CadastroPessoaFisica(daoFactory);
            cpf.setModal(true);
            cpf.setVisible(true);
            vem = (Pessoa) cpf.getUltimoCadastro();
        }else{
            CadastroPessoaJuridica cpj = new CadastroPessoaJuridica(daoFactory);
            cpj.setModal(true);
            cpj.setVisible(true);
            vem = (Pessoa) cpj.getUltimoCadastro();
        }
        if (vem != null) {
            txtIdContraria.setText(vem.getId().toString());
            ContrariaCarrega();
        }
    }
    
	@Action
    /**
     * Prepara formulário para novo cadastro
     */
	public void Novo() {
		ResetaForm();
		txtId.setEnabled(false);
		processo = new Processo();
		processoDAO = daoFactory.getProcessoDAO();
		btnSalvar.setEnabled(true);
	}

    public void VaraCarrega(){
        if (txtIdVara.getText().length() <= 0) return;
        // Busca nova sessao
		VaraDAO varaDAO = daoFactory.getVaraDAO();
		try {
            // Inicia transação
			t = varaDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            vara = varaDAO.findById(
                    Integer.valueOf(txtIdVara.getText()), false);
            
            // Preenche dados no formulário
            txtVaraNome.setText(vara.getNome());

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("vara.errobusca", txtIdVara.getText()));
		}        
    }

    public void AdvogadoCarrega(){
        if (txtIdAdvogado.getText().length() <= 0) return;
        // Busca nova sessao
		AdvogadoDAO advogadoDAO = daoFactory.getAdvogadoDAO();
		try {
            // Inicia transação
			t = advogadoDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            advogado = advogadoDAO.findById(
                    Long.valueOf(txtIdAdvogado.getText()), false);
            
            // Preenche dados no formulário
            txtNomeAdvogado.setText(advogado.getNome());

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("advogado.errobusca", txtIdAdvogado.getText()));
		}        
    }

    public void ClienteCarrega() {
        if (txtIdCliente.getText().length() <= 0) return;
        // Busca nova sessao
       	PessoaDAO pessoaDAO = daoFactory.getPessoaDAO();
		try {
            // Inicia transação
			t = pessoaDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            cliente = pessoaDAO.findById(
                    Long.valueOf(txtIdCliente.getText()), false);
            
            // Preenche dados no formulário
            txtNomeCliente.setText(cliente.getNome());

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("pessoa.errobusca", txtIdCliente.getText()));
		}        
    }
    
    public void ContrariaCarrega() {
        if (txtIdContraria.getText().length() <= 0) return;
        // Busca nova sessao
        PessoaDAO pessoaDAO = daoFactory.getPessoaDAO();
        try {
            // Inicia transação
			t = pessoaDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            contraria = pessoaDAO.findById(
                    Long.valueOf(txtIdContraria.getText()), false);
            
            // Preenche dados no formulário
            txtNomeContraria.setText(contraria.getNome());

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("pessoa.errobusca", txtIdContraria.getText()));
		}        
    }
    
	@Action
    /**
     * Salva novo cadastro ou altera
     */
	public void Salvar() {

        if ((cbPagaTaxa.isSelected()) && (txtValorTaxa.getText().equalsIgnoreCase(""))) {
            JOptionPane.showMessageDialog(null, "Informe um valor de taxa ou desmarque a opção paga taxa");
            txtValorTaxa.requestFocus();
            return;
        }
        
        // se id for nulo trata como inclusão
		if (processo.getId() == null) {
            if (!Seguranca.Permitido("Processos-Dados-inclusao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }
            processo = new Processo();
            processoDAO = daoFactory.getProcessoDAO();
			t = daoFactory.getSessionFactory().getCurrentSession().beginTransaction();
			t.begin();
			try {

                if (txtNumeroProcesso.getText().length() <=0 ) {
                    JOptionPane.showMessageDialog(this, resourceMap.getString("numeroProcesso.informe"));
                    txtNumeroProcesso.requestFocus();
                    return;
                }
                if (vara == null) {
                    JOptionPane.showMessageDialog(this, resourceMap.getString("vara.informe"));
                    txtIdVara.requestFocus();
                    return;
                }
                //Verifica se já existe mesmo numero e vara
                
				if (processoDAO.buscaPorNumeroProcessoVara(txtNumeroProcesso.getText(), vara)
						!= null) {
					JOptionPane.showMessageDialog(
						this,
						resourceMap.getString("jaexiste.processo", 
							String.valueOf(txtNumeroProcesso.getText()), vara.getNome()));
					txtNumeroProcesso.requestFocus();
					return;
				}
                processo.setNumeroProcesso(txtNumeroProcesso.getText());
                processo.setVara(vara);
                
				// Preenche dado nos objetos
                if (advogado == null){
                    JOptionPane.showMessageDialog(this, resourceMap.getString("advogado.informe"));
                    txtIdAdvogado.requestFocus();
                    return;
                }
                processo.setAdvogado(advogado);
                processo.setAdvogadoContraria(txtAdvogadoContraria.getText());
                processo.setArmario(txtArmario.getText());
                processo.setAutor(rbAutor.isSelected());
                processo.setDetalhes(txtDetalhes.getText());
                processo.setGaveta(txtGaveta.getText());
                processo.setObservacao(txtObservacao.getText());

                
                if (cliente == null){
                    JOptionPane.showMessageDialog(this, resourceMap.getString("cliente.informe"));
                    txtIdCliente.requestFocus();
                    return;
                }
                if (contraria == null){
                    JOptionPane.showMessageDialog(this, resourceMap.getString("contraria.informe"));
                    txtIdContraria.requestFocus();
                    return;
                }

                if (rbAutor.isSelected()){
                    processo.setReclamado(contraria);
                    processo.setReclamante(cliente);
                }else{
                    processo.setReclamado(cliente);
                    processo.setReclamante(contraria);
                }
                processo.setRecurso(txtRecurso.getText());
                processo.setTrt(cbTrt.isSelected());
                
                processo.setPagaTaxaAbertura(cbPagaTaxa.isSelected());
                if (cbPagaTaxa.isSelected()){
                    processo.setValorTaxaAbertura(Double.valueOf(formataDouble.parse(txtValorTaxa.getText()).doubleValue()));
                }else{
                    processo.setValorTaxaAbertura(null);
                }
                
                
              
                // Grava 
				processoDAO.makePersistent(processo);
				t.commit();
               
                
                // Confirma
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.sucesso", 
						String.valueOf(processo.getId())));
                // Reseta
                processo = null;
                ResetaForm();
			} catch (Exception e) {
                // Se ocorre algum erro, mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.erro") +
					e.getLocalizedMessage());
                e.printStackTrace();
				t.rollback();
			}


		// Se for alteração
		} else {
            if (!Seguranca.Permitido("Processos-Dados-alteracao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }
            try {
				// Preenche dado nos objetos
                if (advogado == null){
                    JOptionPane.showMessageDialog(this, resourceMap.getString("advogado.informe"));
                    txtIdAdvogado.requestFocus();
                    return;
                }
                processo.setAdvogado(advogado);
                processo.setAdvogadoContraria(txtAdvogadoContraria.getText());
                processo.setArmario(txtArmario.getText());
                processo.setAutor(rbAutor.isSelected());
                processo.setDetalhes(txtDetalhes.getText());
                processo.setGaveta(txtGaveta.getText());
                processo.setObservacao(txtObservacao.getText());

                
                if (cliente == null){
                    JOptionPane.showMessageDialog(this, resourceMap.getString("cliente.informe"));
                    txtIdCliente.requestFocus();
                    return;
                }
                if (contraria == null){
                    JOptionPane.showMessageDialog(this, resourceMap.getString("contraria.informe"));
                    txtIdContraria.requestFocus();
                    return;
                }

                if (rbAutor.isSelected()){
                    processo.setReclamado(contraria);
                    processo.setReclamante(cliente);
                }else{
                    processo.setReclamado(cliente);
                    processo.setReclamante(contraria);
                }
                processo.setRecurso(txtRecurso.getText());
                processo.setTrt(cbTrt.isSelected());

                processo.setPagaTaxaAbertura(cbPagaTaxa.isSelected());
                if (cbPagaTaxa.isSelected()){
                    processo.setValorTaxaAbertura(Double.valueOf(formataDouble.parse(txtValorTaxa.getText()).doubleValue()));
                }else{
                    processo.setValorTaxaAbertura(null);
                }
                
                // Grava alterações
				processoDAO.makePersistent(processo);
				t.commit();
                

                
                // Mostra confirmação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.sucesso"));
                
                // Reinicia formulario
                processo = null;
				ResetaForm();

			} catch (Exception e) {
                // Qualquer erro mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.erro") +
                        e.getLocalizedMessage());
				t.rollback();
			}
		}
	}

    /**
     * Abre cadastro no formulário para alteração
     */
	public void Alterar() {
        // Busca nova sessao
		processoDAO = daoFactory.getProcessoDAO();
		try {
            // Inicia transação
			t = processoDAO.getSession().beginTransaction();
            
            if (txtId.getText().length() > 0){
            // Busca objeto pelo id informado
            processo = processoDAO.findById(
                    Long.valueOf(txtId.getText()), true);
                txtIdVara.setText(processo.getVara().getId().toString());
                txtVaraNome.setText(processo.getVara().getNome());
                txtNumeroProcesso.setText(processo.getNumeroProcesso());
            }else{
                processo = processoDAO.buscaPorNumeroProcessoVara(txtNumeroProcesso.getText(), vara);
            }
            
            
            
            
            // Preenche dados no formulário
            txtAdvogadoContraria.setText(processo.getAdvogadoContraria());
            txtArmario.setText(processo.getArmario());
            txtDetalhes.setText(processo.getDetalhes());
            txtGaveta.setText(processo.getGaveta());
            txtIdAdvogado.setText(processo.getAdvogado().getId().toString());
            AdvogadoCarrega();
            
            if (processo.getAutor()){
                rbAutor.setSelected(true);
                cliente = processo.getReclamante();
                contraria = processo.getReclamado();
            }else{
                rbReu.setSelected(true);
                cliente = processo.getReclamado();
                contraria = processo.getReclamante();                
            }
            txtIdCliente.setText(cliente.getId().toString());
            txtIdContraria.setText(contraria.getId().toString());
            txtNomeCliente.setText(cliente.getNome());
            txtNomeContraria.setText(contraria.getNome());
            txtObservacao.setText(processo.getObservacao());
            txtRecurso.setText(processo.getRecurso());
            
            
            if (cliente instanceof PessoaFisica){
                rbClienteFisica.setSelected(true);
            }else{
                rbClienteJuridica.setSelected(true);
            }
            
            if (contraria instanceof PessoaFisica){
                rbContrariaFisica.setSelected(true);
            }else{
                rbContrariaJuridica.setSelected(true);
            }
            
            cbTrt.setSelected(processo.getTrt());
            
            cbPagaTaxa.setSelected(processo.getPagaTaxaAbertura());
            if (processo.getPagaTaxaAbertura()){
                txtValorTaxa.setText(formataDouble.format(processo.getValorTaxaAbertura()));
                PagaTaxa();
            }
            
            // Ativa controles disponíveis
			btnSalvar.setEnabled(true);
			btnExcluir.setEnabled(true);
            txtId.setEnabled(false);
            txtIdVara.setEnabled(false);
            btnPesqVara.setEnabled(false);
            txtNumeroProcesso.setEnabled(false);
            jTabbedPane1.setSelectedIndex(0);

		} catch (Exception e) {
            // Se não acha, nostra mensagem
            e.printStackTrace();
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("altera.errobusca", txtId.getText()));
			txtId.setEnabled(true);
			btnSalvar.setEnabled(false);
			btnExcluir.setEnabled(false);
			txtId.requestFocus();
		}
	}

	@Action
    /**
     * Limpa formulário, cancelando edição atual
     */
	public void Cancelar() {
		processo = null;
		ResetaForm();
	}
	
	@Action
    /**
     * Exclui objeto atual
     */
	public void Excluir() {
        
        if (!Seguranca.Permitido("Processos-Dados-exclusao")) {
            JOptionPane.showMessageDialog(null, "Sem permissão");
            return;
        }
        
		// Solicita confirmação
        int opcao = JOptionPane.showConfirmDialog(this,
                resourceMap.getString("exclui.confirmacao"),
                resourceMap.getString("exclui.confirmacao.titulo"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        switch (opcao) {
			case 0: // Resposta sim
				try {
                    // Remove da persistencia
					processoDAO.makeTransient(processo);
					t.commit();
                    // Confirma
					JOptionPane.showMessageDialog(this,
						resourceMap.getString("exclui.ok"));
                    // Limpa form
					processo = null;
					ResetaForm();

				} catch (Exception e) {
                    // Dando erro diz que não é possivel
					JOptionPane.showMessageDialog(this,
						resourceMap.getString(
						"exclui.naopode"));
				}
				break;
			case 1: // Resposta não
				break;
		}

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alerta;
    private javax.swing.ButtonGroup bgCliente;
    private javax.swing.ButtonGroup bgParteContraria;
    private javax.swing.ButtonGroup bgPosicao;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnClienteCadastrar;
    private javax.swing.JButton btnContrariaCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesqAdvogado;
    private javax.swing.JButton btnPesqVara;
    private javax.swing.JButton btnPesquisaCliente;
    private javax.swing.JButton btnPesquisaContraria;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox cbPagaTaxa;
    private javax.swing.JCheckBox cbTrt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpDetalhes;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lNumProcesso;
    private javax.swing.JLabel lVara;
    private javax.swing.JRadioButton rbAutor;
    private javax.swing.JRadioButton rbClienteFisica;
    private javax.swing.JRadioButton rbClienteJuridica;
    private javax.swing.JRadioButton rbContrariaFisica;
    private javax.swing.JRadioButton rbContrariaJuridica;
    private javax.swing.JRadioButton rbReu;
    private javax.swing.JTextField txtAdvogadoContraria;
    private javax.swing.JTextField txtArmario;
    private javax.swing.JEditorPane txtDetalhes;
    private javax.swing.JTextField txtGaveta;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JTextField txtIdAdvogado;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdContraria;
    private javax.swing.JTextField txtIdVara;
    private javax.swing.JTextField txtNomeAdvogado;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeContraria;
    private javax.swing.JFormattedTextField txtNumeroProcesso;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtRecurso;
    private javax.swing.JFormattedTextField txtValorTaxa;
    private javax.swing.JTextField txtVaraNome;
    // End of variables declaration//GEN-END:variables

	public SchedulaDAOFactory getDaoFactory() {
		return daoFactory;
	}

	public void setDaoFactory(SchedulaDAOFactory daoFactory) {
		this.daoFactory = daoFactory;
	}

}
