/*
 * CadastroPessoaFisicas.java
 *
 * Created on May 27, 2008, 12:02 AM
 */

package br.com.perettis.schedula;

import br.com.perettis.gets.dao.DAOConstants;
import br.com.perettis.gets.swing.FormSearch;
import br.com.perettis.gets.swing.NumericDocument;
import br.com.perettis.gets.swing.GetsDocument;
import br.com.perettis.gets.swing.OnEnterTab;
import br.com.perettis.gets.text.Filters;
import br.com.perettis.gets.validators.DocumentsBR;
import br.com.perettis.gets.validators.Email;
import br.com.perettis.schedula.entity.PessoaFisica;
import br.com.perettis.schedula.entity.EstadoCivil;
import br.com.perettis.schedula.entity.Uf;
import br.com.perettis.schedula.model.PessoaFisicaDAO;
import br.com.perettis.schedula.model.EstadoCivilDAO;
import br.com.perettis.schedula.model.SchedulaDAOFactory;
import br.com.perettis.schedula.model.Seguranca;
import br.com.perettis.schedula.model.UfDAO;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Transaction;
import org.jdesktop.application.Action;

/**
 *
 * @author  vinicius
 */
public class CadastroPessoaFisica extends javax.swing.JDialog {

    PessoaFisica pessoaFisica;
    private PessoaFisica ultimoCadastro;
    PessoaFisicaDAO pessoaFisicaDAO;
    private SchedulaDAOFactory daoFactory;
    Transaction t;
    org.jdesktop.application.ResourceMap resourceMap;
    FormSearch<Long, PessoaFisica, PessoaFisicaDAO> pesquisa;
    
    
    
    /** Creates new form CadastroPessoaFisicas */
    public CadastroPessoaFisica(SchedulaDAOFactory daoF) {
        setDaoFactory(daoF);
        initComponents();
        setModal(false);
        new OnEnterTab(getContentPane());
        ResetaForm();
        resourceMap = org.jdesktop.application.Application.getInstance(
                br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroPessoaFisica.class);
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabDados = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbEstadoCivil = new javax.swing.JComboBox();
        txtProfissao = new javax.swing.JTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        txtNomeMae = new javax.swing.JTextField();
        txtNomePai = new javax.swing.JTextField();
        txtNacionalidade = new javax.swing.JTextField();
        txtNaturalidade = new javax.swing.JTextField();
        jxdDataNascimento = new org.jdesktop.swingx.JXDatePicker();
        tabDocumentos = new javax.swing.JPanel();
        lCPF = new javax.swing.JLabel();
        lRG = new javax.swing.JLabel();
        lOE = new javax.swing.JLabel();
        lCT = new javax.swing.JLabel();
        lCTSerie = new javax.swing.JLabel();
        lOAB = new javax.swing.JLabel();
        lOABUF = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        txtOE = new javax.swing.JTextField();
        txtCT = new javax.swing.JTextField();
        txtCTSerie = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        tabEndereco = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        cbUf = new javax.swing.JComboBox();
        txtCep = new javax.swing.JFormattedTextField();
        tabContatos = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtFone1 = new javax.swing.JTextField();
        txtFone2 = new javax.swing.JTextField();
        txtFone3 = new javax.swing.JTextField();
        txtContato1 = new javax.swing.JTextField();
        txtContato2 = new javax.swing.JTextField();
        txtContato3 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        tabObservacao = new javax.swing.JPanel();
        sclObservacao = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroPessoaFisica.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImage(new Imagens().getIcone());
        setName("Form"); // NOI18N

        txtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId.setName("txtId"); // NOI18N
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });

        txtNome.setName("txtNome"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        tabDados.setName("tabDados"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        cbEstadoCivil.setName("cbEstadoCivil"); // NOI18N

        txtProfissao.setName("txtProfissao"); // NOI18N

        bgSexo.add(rbMasculino);
        rbMasculino.setText(resourceMap.getString("rbMasculino.text")); // NOI18N
        rbMasculino.setName("rbMasculino"); // NOI18N

        bgSexo.add(rbFeminino);
        rbFeminino.setText(resourceMap.getString("rbFeminino.text")); // NOI18N
        rbFeminino.setName("rbFeminino"); // NOI18N

        txtNomeMae.setName("txtNomeMae"); // NOI18N

        txtNomePai.setName("txtNomePai"); // NOI18N

        txtNacionalidade.setName("txtNacionalidade"); // NOI18N

        txtNaturalidade.setName("txtNaturalidade"); // NOI18N

        jxdDataNascimento.setFormats("dd/MM/yyyy");
        jxdDataNascimento.setName("jxdDataNascimento"); // NOI18N

        javax.swing.GroupLayout tabDadosLayout = new javax.swing.GroupLayout(tabDados);
        tabDados.setLayout(tabDadosLayout);
        tabDadosLayout.setHorizontalGroup(
            tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDadosLayout.createSequentialGroup()
                        .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomePai, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                            .addComponent(txtNomeMae, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                            .addComponent(txtNacionalidade, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                            .addComponent(txtNaturalidade, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)))
                    .addGroup(tabDadosLayout.createSequentialGroup()
                        .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tabDadosLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDadosLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(3, 3, 3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDadosLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(3, 3, 3)))
                        .addGap(3, 3, 3)
                        .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jxdDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabDadosLayout.createSequentialGroup()
                                .addComponent(rbMasculino)
                                .addGap(41, 41, 41)
                                .addComponent(rbFeminino))
                            .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProfissao, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))))
                .addContainerGap())
        );
        tabDadosLayout.setVerticalGroup(
            tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabDadosLayout.createSequentialGroup()
                        .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jxdDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMasculino)
                            .addComponent(jLabel7)))
                    .addComponent(rbFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(13, 13, 13)
                .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        cbEstadoCivilMonta();
        new GetsDocument().setMaxLenght(255, txtProfissao);
        new GetsDocument().setMaxLenght(100, txtNomeMae);
        new GetsDocument().setMaxLenght(100, txtNomePai);
        new GetsDocument().setMaxLenght(50, txtNacionalidade);
        new GetsDocument().setMaxLenght(50, txtNaturalidade);

        jTabbedPane1.addTab(resourceMap.getString("tabDados.TabConstraints.tabTitle"), tabDados); // NOI18N

        tabDocumentos.setName("tabDocumentos"); // NOI18N

        lCPF.setText(resourceMap.getString("lCPF.text")); // NOI18N
        lCPF.setName("lCPF"); // NOI18N

        lRG.setText(resourceMap.getString("lRG.text")); // NOI18N
        lRG.setName("lRG"); // NOI18N

        lOE.setText(resourceMap.getString("lOE.text")); // NOI18N
        lOE.setName("lOE"); // NOI18N

        lCT.setText(resourceMap.getString("lCT.text")); // NOI18N
        lCT.setName("lCT"); // NOI18N

        lCTSerie.setText(resourceMap.getString("lCTSerie.text")); // NOI18N
        lCTSerie.setName("lCTSerie"); // NOI18N

        lOAB.setName("lOAB"); // NOI18N

        lOABUF.setName("lOABUF"); // NOI18N

        txtRG.setName("txtRG"); // NOI18N

        txtOE.setName("txtOE"); // NOI18N

        txtCT.setName("txtCT"); // NOI18N

        txtCTSerie.setName("txtCTSerie"); // NOI18N

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setName("txtCpf"); // NOI18N

        javax.swing.GroupLayout tabDocumentosLayout = new javax.swing.GroupLayout(tabDocumentos);
        tabDocumentos.setLayout(tabDocumentosLayout);
        tabDocumentosLayout.setHorizontalGroup(
            tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCT, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lCTSerie)
                .addGap(1, 1, 1)
                .addComponent(txtCTSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(tabDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lOAB)
                .addGap(180, 180, 180)
                .addComponent(lOABUF)
                .addContainerGap(306, Short.MAX_VALUE))
            .addGroup(tabDocumentosLayout.createSequentialGroup()
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDocumentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lRG))
                    .addGroup(tabDocumentosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lCPF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDocumentosLayout.createSequentialGroup()
                        .addComponent(txtRG, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lOE)
                        .addGap(1, 1, 1)
                        .addComponent(txtOE, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(tabDocumentosLayout.createSequentialGroup()
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        tabDocumentosLayout.setVerticalGroup(
            tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCPF)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtOE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lOE))
                    .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lRG)))
                .addGap(18, 18, 18)
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCTSerie)
                    .addComponent(lCT)
                    .addComponent(txtCTSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lOAB)
                    .addComponent(lOABUF))
                .addGap(143, 143, 143))
        );

        new GetsDocument().setMaxLenght(100, txtRG);
        new GetsDocument().setMaxLenght(10, txtOE);
        new GetsDocument().setMaxLenght(20, txtCT);
        new GetsDocument().setMaxLenght(10, txtCTSerie);

        jTabbedPane1.addTab(resourceMap.getString("tabDocumentos.TabConstraints.tabTitle"), tabDocumentos); // NOI18N

        tabEndereco.setName("tabEndereco"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        txtEndereco.setName("txtEndereco"); // NOI18N

        txtBairro.setName("txtBairro"); // NOI18N

        txtCidade.setName("txtCidade"); // NOI18N

        cbUf.setName("cbUf"); // NOI18N

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setName("txtCep"); // NOI18N

        javax.swing.GroupLayout tabEnderecoLayout = new javax.swing.GroupLayout(tabEndereco);
        tabEndereco.setLayout(tabEnderecoLayout);
        tabEnderecoLayout.setHorizontalGroup(
            tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbUf, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCidade, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        tabEnderecoLayout.setVerticalGroup(
            tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEnderecoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        new GetsDocument().setMaxLenght(255, txtEndereco);
        new GetsDocument().setMaxLenght(255, txtBairro);
        new GetsDocument().setMaxLenght(100, txtCidade);
        cbUfMonta();

        jTabbedPane1.addTab(resourceMap.getString("tabEndereco.TabConstraints.tabTitle"), tabEndereco); // NOI18N

        tabContatos.setName("tabContatos"); // NOI18N

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        txtFone1.setName("txtFone1"); // NOI18N

        txtFone2.setName("txtFone2"); // NOI18N

        txtFone3.setName("txtFone3"); // NOI18N

        txtContato1.setName("txtContato1"); // NOI18N

        txtContato2.setName("txtContato2"); // NOI18N

        txtContato3.setName("txtContato3"); // NOI18N

        txtEmail.setName("txtEmail"); // NOI18N

        javax.swing.GroupLayout tabContatosLayout = new javax.swing.GroupLayout(tabContatos);
        tabContatos.setLayout(tabContatosLayout);
        tabContatosLayout.setHorizontalGroup(
            tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabContatosLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
                    .addGroup(tabContatosLayout.createSequentialGroup()
                        .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFone3)
                            .addComponent(txtFone2)
                            .addComponent(txtFone1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabContatosLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContato2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                            .addGroup(tabContatosLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContato3, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                            .addGroup(tabContatosLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContato1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        tabContatosLayout.setVerticalGroup(
            tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(txtFone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(txtFone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(txtFone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        new GetsDocument().setMaxLenght(20, txtFone1);
        new GetsDocument().setMaxLenght(20, txtFone2);
        new GetsDocument().setMaxLenght(20, txtFone3);
        new GetsDocument().setMaxLenght(20, txtContato1);
        new GetsDocument().setMaxLenght(20, txtContato2);
        new GetsDocument().setMaxLenght(20, txtContato3);
        new GetsDocument().setMaxLenght(255, txtEmail);

        jTabbedPane1.addTab(resourceMap.getString("tabContatos.TabConstraints.tabTitle"), tabContatos); // NOI18N

        tabObservacao.setName("tabObservacao"); // NOI18N

        sclObservacao.setName("sclObservacao"); // NOI18N

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        txtObservacao.setName("txtObservacao"); // NOI18N
        sclObservacao.setViewportView(txtObservacao);

        javax.swing.GroupLayout tabObservacaoLayout = new javax.swing.GroupLayout(tabObservacao);
        tabObservacao.setLayout(tabObservacaoLayout);
        tabObservacaoLayout.setHorizontalGroup(
            tabObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(tabObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabObservacaoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sclObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        tabObservacaoLayout.setVerticalGroup(
            tabObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
            .addGroup(tabObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabObservacaoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sclObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab(resourceMap.getString("tabObservacao.TabConstraints.tabTitle"), tabObservacao); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getActionMap(CadastroPessoaFisica.class, this);
        btnSalvar.setAction(actionMap.get("Salvar")); // NOI18N
        btnSalvar.setName("btnSalvar"); // NOI18N

        btnCancelar.setAction(actionMap.get("Cancelar")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        btnExcluir.setAction(actionMap.get("Excluir")); // NOI18N
        btnExcluir.setName("btnExcluir"); // NOI18N

        btnNovo.setAction(actionMap.get("Novo")); // NOI18N
        btnNovo.setName("btnNovo"); // NOI18N

        btnPesquisar.setAction(actionMap.get("Pesquisar")); // NOI18N
        btnPesquisar.setName("btnPesquisar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar))
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnNovo)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );

        new NumericDocument().setMaxLenght(12,txtId);
        GetsDocument gdNome = new GetsDocument();
        gdNome.setMaxLenght(100);
        txtNome.setDocument(gdNome);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-538)/2, (screenSize.height-512)/2, 538, 512);
    }// </editor-fold>//GEN-END:initComponents

private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
    if (!txtId.getText().equalsIgnoreCase("")) {
        Alterar();
    }
}//GEN-LAST:event_txtIdFocusLost

private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_F10) {
        Pesquisar();
    }
}//GEN-LAST:event_txtIdKeyPressed


    /**
     * Reinicia formulário
     */
  	public void ResetaForm() {
		txtId.setText("");
        txtBairro.setText("");
        txtCT.setText("");
        txtCTSerie.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtContato1.setText("");
        txtContato2.setText("");
        txtContato3.setText("");
        txtCpf.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtFone1.setText("");
        txtFone2.setText("");
        txtFone3.setText("");
        txtNacionalidade.setText("");
        txtNaturalidade.setText("");
        txtNome.setText("");
        txtNomeMae.setText("");
        txtNomePai.setText("");
        txtOE.setText("");
        txtObservacao.setText("");
        txtProfissao.setText("");
        txtRG.setText("");
        
        jxdDataNascimento.setDate(null);
        
        cbEstadoCivil.setSelectedIndex(-1);
        cbUf.setSelectedIndex(-1);
        
        
        jTabbedPane1.setSelectedIndex(0);
        rbMasculino.setSelected(true);
		txtId.setEnabled(true);
		txtId.requestFocus();
		btnSalvar.setEnabled(false);
		btnExcluir.setEnabled(false);
	}

    @Action
    /**
     * Abre tela de pesquisa
     */
    public void Pesquisar(){
        if (pesquisa == null) {
            pesquisa = new PesquisaPessoaFisica(getDaoFactory());
        }
        
        pesquisa.setTitle("Selecione a Pessoa Física para Alteração.");
        pesquisa.doSearch();
        pesquisa.openSearch();
        PessoaFisica vem = pesquisa.getEntity();
        if (vem != null){
            txtId.setText(String.valueOf(vem.getId()));
            Alterar();
        }
    }
    

    @Action
    /**
     * Prepara formulário para novo cadastro
     */
	public void Novo() {
		ResetaForm();
		txtId.setEnabled(false);
		pessoaFisica = new PessoaFisica();
		pessoaFisicaDAO = daoFactory.getPessoaFisicaDAO();
		btnSalvar.setEnabled(true);
	}
        
    	@Action
    /**
     * Salva novo cadastro ou altera
     */
	public void Salvar() {

        // se id for nulo trata como inclusão
		if (pessoaFisica.getId() == null) {
            
            if (!Seguranca.Permitido("Cadastro-PessoaFisica-inclusao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }

            
            pessoaFisica = new PessoaFisica();
			t = pessoaFisicaDAO.getSession().beginTransaction();
			t.begin();
			try {

				// Preenche dado nos objetos
                pessoaFisica.setBairro(txtBairro.getText());
                
                
                //TODO COLOCAR NO DAO PESSOA FISICA BUSCA POR CARTEIRA DE TRABALHO E VERIFICAR AQUI
                if (!txtCT.getText().equalsIgnoreCase("")){
                    pessoaFisica.setCarteiraTrabalho(txtCT.getText());
                }else{
                    pessoaFisica.setCarteiraTrabalho(null);
                }
                if (!txtCTSerie.getText().equalsIgnoreCase("")){
                    pessoaFisica.setCarteiraTrabalhoSerie(txtCTSerie.getText());
                }else{
                    pessoaFisica.setCarteiraTrabalhoSerie(null);
                }
                
                pessoaFisica.setCep(txtCep.getText());
                pessoaFisica.setCidade(txtCidade.getText());
                pessoaFisica.setContato1(txtContato1.getText());
                pessoaFisica.setContato2(txtContato2.getText());
                pessoaFisica.setContato3(txtContato3.getText());                

                if (!Filters.onlyNumbers(txtCpf.getText()).equalsIgnoreCase("")) {
                    if (!DocumentsBR.CPF(txtCpf.getText())) {
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.cpf",
                                String.valueOf(txtCpf.getText())));
                        txtCpf.requestFocus();
                        return;
                    }
                    //Verifica se já existe mesmo cpf
                    if (pessoaFisicaDAO.buscaPorCpf(Filters.onlyNumbers(txtCpf.getText())) != null) {
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("jaexiste.cpf",
                                String.valueOf(txtCpf.getText())));
                        txtCpf.requestFocus();
                        return;
                    }
                    pessoaFisica.setCpf(Filters.onlyNumbers(txtCpf.getText()));
                }else{
                    pessoaFisica.setCpf(null);
                }

                
                
                if (jxdDataNascimento.getDate() != null) {
                    if (jxdDataNascimento.getDate().after(new Date())) {
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.dataNascimento"));
                        jxdDataNascimento.requestFocus();
                        return;
                    }
                    pessoaFisica.setDataNascimento(jxdDataNascimento.getDate());
                }
                
                
                if ((txtEmail.getText().length() > 0)&& (!Email.validSintax(txtEmail.getText()))){
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.email", txtEmail.getText()));
                        txtEmail.requestFocus();
                        return;                    
                }
                pessoaFisica.setEmail(txtEmail.getText());
                pessoaFisica.setEndereco(txtEndereco.getText());
                pessoaFisica.setEstadoCivil((EstadoCivil) cbEstadoCivil.getSelectedItem());
                pessoaFisica.setFone1(txtFone1.getText());
                pessoaFisica.setFone2(txtFone2.getText());
                pessoaFisica.setFone3(txtFone3.getText());
                pessoaFisica.setNacionalidade(txtNacionalidade.getText());
                pessoaFisica.setNaturalidade(txtNaturalidade.getText());
                
                if(txtNome.getText().length() <=0){
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.nome",txtNome.getText()));
                        txtNome.requestFocus();
                        return;                    
                }
                pessoaFisica.setNome(txtNome.getText());
                
                pessoaFisica.setNomeMae(txtNomeMae.getText());
                pessoaFisica.setNomePai(txtNomePai.getText());
                pessoaFisica.setObservacao(txtObservacao.getText());
                pessoaFisica.setProfissao(txtProfissao.getText());

                //TODO COLOCAR BUSCA POR RG E COLOCAR AQUI
                if (!txtRG.getText().equalsIgnoreCase("")) {
                    pessoaFisica.setRg(txtRG.getText());
                }else{
                    pessoaFisica.setRg(null);
                }
                if (!txtOE.getText().equalsIgnoreCase("")) {
                    pessoaFisica.setRgOrgaoExpeditor(txtOE.getText());
                }else{
                    pessoaFisica.setRgOrgaoExpeditor(null);
                }
                
                pessoaFisica.setSexo(rbMasculino.isSelected());
                pessoaFisica.setUf((Uf) cbUf.getSelectedItem());
                
                
                // Grava 
				pessoaFisicaDAO.makePersistent(pessoaFisica);
				t.commit();
                
                // Confirma
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.sucesso", 
						String.valueOf(pessoaFisica.getId())));
                
                setUltimoCadastro(pessoaFisica);
                // Reseta
                pessoaFisica = null;
                ResetaForm();
			} catch (ExceptionInInitializerError e) {
                // Se ocorre algum erro, mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.erro") +
					e.getLocalizedMessage());
				t.rollback();
			}

		// Se for alteração
		} else {
            
            if (!Seguranca.Permitido("Cadastro-PessoaFisica-alteracao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }

            
            try {
                // Preenche dado nos objetos
                pessoaFisica.setBairro(txtBairro.getText());
                
                //TODO COLOCAR NO DAO PESSOA FISICA BUSCA POR CARTEIRA DE TRABALHO E VERIFICAR AQUI
                if (!txtCT.getText().equalsIgnoreCase("")){
                    pessoaFisica.setCarteiraTrabalho(txtCT.getText());
                }else{
                    pessoaFisica.setCarteiraTrabalho(null);
                }
                if (!txtCTSerie.getText().equalsIgnoreCase("")){
                    pessoaFisica.setCarteiraTrabalhoSerie(txtCTSerie.getText());
                }else{
                    pessoaFisica.setCarteiraTrabalhoSerie(null);
                }
                
                pessoaFisica.setCep(txtCep.getText());
                pessoaFisica.setCidade(txtCidade.getText());
                pessoaFisica.setContato1(txtContato1.getText());
                pessoaFisica.setContato2(txtContato2.getText());
                pessoaFisica.setContato3(txtContato3.getText());                

                if (!Filters.onlyNumbers(txtCpf.getText()).equalsIgnoreCase("")) {
                    if (!DocumentsBR.CPF(txtCpf.getText())) {
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.cpf",
                                String.valueOf(txtCpf.getText())));
                        txtCpf.requestFocus();
                        return;
                    }
                    
                    
                    // Verifica se existe outro com mesmos dados
                    PessoaFisica outro = pessoaFisicaDAO.buscaPorCpf(Filters.onlyNumbers(txtCpf.getText()));
                    if (outro != null) {
                        if (outro.getId() != pessoaFisica.getId()) {

                            JOptionPane.showMessageDialog(this,
                                    resourceMap.getString("jaexiste.cpf",
                                    String.valueOf(txtCpf.getText())));
                            txtCpf.requestFocus();
                            return;
                        }
                    }
                    pessoaFisica.setCpf(Filters.onlyNumbers(txtCpf.getText()));
                } else {
                    pessoaFisica.setCpf(null);
                }

                if (jxdDataNascimento.getDate() != null) {
                    if (jxdDataNascimento.getDate().after(new Date())) {
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.dataNascimento"));
                        jxdDataNascimento.requestFocus();
                        return;
                    }
                    pessoaFisica.setDataNascimento(jxdDataNascimento.getDate());
                }

                if ((txtEmail.getText().length() > 0)&& (!Email.validSintax(txtEmail.getText()))){
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.email",txtEmail.getText()));
                        txtEmail.requestFocus();
                        return;                    
                }
                pessoaFisica.setEmail(txtEmail.getText());

                pessoaFisica.setEndereco(txtEndereco.getText());
                pessoaFisica.setEstadoCivil((EstadoCivil) cbEstadoCivil.getSelectedItem());
                pessoaFisica.setFone1(txtFone1.getText());
                pessoaFisica.setFone2(txtFone2.getText());
                pessoaFisica.setFone3(txtFone3.getText());
                pessoaFisica.setNacionalidade(txtNacionalidade.getText());
                pessoaFisica.setNaturalidade(txtNaturalidade.getText());
                
                if(txtNome.getText().length() <=0){
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.nome"));
                        txtNome.requestFocus();
                        return;                    
                }
                pessoaFisica.setNome(txtNome.getText());
                
                pessoaFisica.setNomeMae(txtNomeMae.getText());
                pessoaFisica.setNomePai(txtNomePai.getText());
                pessoaFisica.setObservacao(txtObservacao.getText());
                pessoaFisica.setProfissao(txtProfissao.getText());
                
                if (!txtRG.getText().equalsIgnoreCase("")) {
                    pessoaFisica.setRg(txtRG.getText());
                }else{
                    pessoaFisica.setRg(null);
                }
                if (!txtOE.getText().equalsIgnoreCase("")) {
                    pessoaFisica.setRgOrgaoExpeditor(txtOE.getText());
                }else{
                    pessoaFisica.setRgOrgaoExpeditor(null);
                }                pessoaFisica.setSexo(rbMasculino.isSelected());
                pessoaFisica.setUf((Uf) cbUf.getSelectedItem());
                
                // Grava alterações
				pessoaFisicaDAO.makePersistent(pessoaFisica);
				t.commit();
                
                // Mostra confirmação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.sucesso"));
                
                // Reinicia formulario
                pessoaFisica = null;
				ResetaForm();

			} catch (Exception e) {
                // Qualquer erro mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.erro") +
                        e.getLocalizedMessage());
				t.rollback();
                e.printStackTrace();
			}
		}
	}

    /**
     * Abre cadastro no formulário para alteração
     */
	public void Alterar() {
        // Busca nova sessao
		pessoaFisicaDAO = daoFactory.getPessoaFisicaDAO();
		try {
            // Inicia transação
			t = pessoaFisicaDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            pessoaFisica = pessoaFisicaDAO.findById(
                    Long.valueOf(txtId.getText()), true);
            
            // Preenche dados no formulário
            txtBairro.setText(pessoaFisica.getBairro());
            txtCT.setText(pessoaFisica.getCarteiraTrabalho());
            txtCTSerie.setText(pessoaFisica.getCarteiraTrabalhoSerie());
            txtCep.setText(pessoaFisica.getCep());
            txtCidade.setText(pessoaFisica.getCidade());
            txtContato1.setText(pessoaFisica.getContato1());
            txtContato2.setText(pessoaFisica.getContato2());
            txtContato3.setText(pessoaFisica.getContato3());
            if (pessoaFisica.getCpf()!=null) {
                txtCpf.setText(pessoaFisica.getCpf());
            }else{
                txtCpf.setText("");
            }
            txtEmail.setText(pessoaFisica.getEmail());
            txtEndereco.setText(pessoaFisica.getEndereco());
            txtFone1.setText(pessoaFisica.getFone1());
            txtFone2.setText(pessoaFisica.getFone2());
            txtFone3.setText(pessoaFisica.getFone3());
            txtNacionalidade.setText(pessoaFisica.getNacionalidade());
            txtNaturalidade.setText(pessoaFisica.getNaturalidade());
            txtNome.setText(pessoaFisica.getNome());
            txtNomeMae.setText(pessoaFisica.getNomeMae());
            txtNomePai.setText(pessoaFisica.getNomePai());
            txtOE.setText(pessoaFisica.getRgOrgaoExpeditor());
            txtObservacao.setText(pessoaFisica.getObservacao());
            txtProfissao.setText(pessoaFisica.getProfissao());
            txtRG.setText(pessoaFisica.getRg());
            
            if (pessoaFisica.getSexo()){
                rbMasculino.setSelected(true);
            }else{
                rbFeminino.setSelected(true);
            }
            
            jxdDataNascimento.setDate(pessoaFisica.getDataNascimento());
            
            cbEstadoCivil.setSelectedItem(pessoaFisica.getEstadoCivil());
            cbUf.setSelectedItem(pessoaFisica.getUf());
            
            
            // Ativa controles disponíveis
			btnSalvar.setEnabled(true);
			btnExcluir.setEnabled(true);
            txtId.setEnabled(false);

		} catch (Exception e) {
            e.printStackTrace();
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("altera.errobusca", txtId.getText()));
			txtId.setEnabled(true);
			btnSalvar.setEnabled(false);
			btnExcluir.setEnabled(false);
			txtId.requestFocus();
		}
	}
    
    @Action
    /**
     * Limpa formulário, cancelando edição atual
     */
	public void Cancelar() {
		pessoaFisica = null;
		ResetaForm();
	}
	
	@Action
    /**
     * Exclui objeto atual
     */
	public void Excluir() {
        
        if (!Seguranca.Permitido("Cadastro-PessoaFisica-exclusao")) {
            JOptionPane.showMessageDialog(null, "Sem permissão");
            return;
        }

        
		// Solicita confirmação
        int opcao = JOptionPane.showConfirmDialog(this,
                resourceMap.getString("exclui.confirmacao"),
                resourceMap.getString("exclui.confirmacao.titulo"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        switch (opcao) {
			case 0: // Resposta sim
				try {
                    // Remove da persistencia
					pessoaFisicaDAO.makeTransient(pessoaFisica);
					t.commit();
                    // Confirma
					JOptionPane.showMessageDialog(this,
						resourceMap.getString("exclui.ok"));
                    // Limpa form
					pessoaFisica = null;
					ResetaForm();

				} catch (Exception e) {
                    // Dando erro diz que não é possivel
					JOptionPane.showMessageDialog(this,
						resourceMap.getString(
						"exclui.naopode"));
				}
				break;
			case 1: // Resposta não
				break;
		}

	}

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.ButtonGroup bgSexo;
    javax.swing.JButton btnCancelar;
    javax.swing.JButton btnExcluir;
    javax.swing.JButton btnNovo;
    javax.swing.JButton btnPesquisar;
    javax.swing.JButton btnSalvar;
    javax.swing.JComboBox cbEstadoCivil;
    javax.swing.JComboBox cbUf;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel14;
    javax.swing.JLabel jLabel15;
    javax.swing.JLabel jLabel16;
    javax.swing.JLabel jLabel17;
    javax.swing.JLabel jLabel18;
    javax.swing.JLabel jLabel19;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel20;
    javax.swing.JLabel jLabel21;
    javax.swing.JLabel jLabel22;
    javax.swing.JLabel jLabel23;
    javax.swing.JLabel jLabel24;
    javax.swing.JLabel jLabel25;
    javax.swing.JLabel jLabel26;
    javax.swing.JLabel jLabel27;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JTabbedPane jTabbedPane1;
    org.jdesktop.swingx.JXDatePicker jxdDataNascimento;
    javax.swing.JLabel lCPF;
    javax.swing.JLabel lCT;
    javax.swing.JLabel lCTSerie;
    javax.swing.JLabel lOAB;
    javax.swing.JLabel lOABUF;
    javax.swing.JLabel lOE;
    javax.swing.JLabel lRG;
    javax.swing.JRadioButton rbFeminino;
    javax.swing.JRadioButton rbMasculino;
    javax.swing.JScrollPane sclObservacao;
    javax.swing.JPanel tabContatos;
    javax.swing.JPanel tabDados;
    javax.swing.JPanel tabDocumentos;
    javax.swing.JPanel tabEndereco;
    javax.swing.JPanel tabObservacao;
    javax.swing.JTextField txtBairro;
    javax.swing.JTextField txtCT;
    javax.swing.JTextField txtCTSerie;
    javax.swing.JFormattedTextField txtCep;
    javax.swing.JTextField txtCidade;
    javax.swing.JTextField txtContato1;
    javax.swing.JTextField txtContato2;
    javax.swing.JTextField txtContato3;
    javax.swing.JFormattedTextField txtCpf;
    javax.swing.JTextField txtEmail;
    javax.swing.JTextField txtEndereco;
    javax.swing.JTextField txtFone1;
    javax.swing.JTextField txtFone2;
    javax.swing.JTextField txtFone3;
    javax.swing.JTextField txtId;
    javax.swing.JTextField txtNacionalidade;
    javax.swing.JTextField txtNaturalidade;
    javax.swing.JTextField txtNome;
    javax.swing.JTextField txtNomeMae;
    javax.swing.JTextField txtNomePai;
    javax.swing.JTextField txtOE;
    javax.swing.JTextArea txtObservacao;
    javax.swing.JTextField txtProfissao;
    javax.swing.JTextField txtRG;
    // End of variables declaration//GEN-END:variables


    private void cbEstadoCivilMonta() {
        EstadoCivilDAO estadoCivilDAO =  getDaoFactory().getEstadoCivilDAO();
        Transaction t = estadoCivilDAO.getSession().getTransaction();
        t.begin();
        List<EstadoCivil> esList = estadoCivilDAO.findByPropertyLike("desabilitado", false, DAOConstants.EQUAL, "descricao");
        Iterator<EstadoCivil> itEs = esList.iterator();
        while (itEs.hasNext()) {
            cbEstadoCivil.addItem(itEs.next());
        }
    }
    
   
    private void cbUfMonta() {
        UfDAO ufDAO =  getDaoFactory().getUfDAO();
        Transaction tuf = ufDAO.getSession().getTransaction();
        tuf.begin();
        List<Uf> list = ufDAO.findAll();
        Iterator<Uf> it = list.iterator();
        while (it.hasNext()) {
            cbUf.addItem(it.next());
        }
    }

    public

    SchedulaDAOFactory getDaoFactory() {
        return daoFactory;
    }

    public void setDaoFactory(SchedulaDAOFactory daoFactory) {
        this.daoFactory = daoFactory;
    }

    public PessoaFisica getUltimoCadastro() {
        return ultimoCadastro;
    }

    public void setUltimoCadastro(PessoaFisica ultimoCadastro) {
        this.ultimoCadastro = ultimoCadastro;
    }
}

