/*
 * CadastroPessoaJuridica.java
 *
 * Created on May 27, 2008, 12:02 AM
 */

package br.com.perettis.schedula;

import br.com.perettis.gets.swing.FormSearch;
import br.com.perettis.gets.swing.NumericDocument;
import br.com.perettis.gets.swing.GetsDocument;
import br.com.perettis.gets.swing.OnEnterTab;
import br.com.perettis.gets.text.Filters;
import br.com.perettis.gets.validators.DocumentsBR;
import br.com.perettis.gets.validators.Email;
import br.com.perettis.schedula.entity.PessoaJuridica;
import br.com.perettis.schedula.entity.Uf;
import br.com.perettis.schedula.model.PessoaJuridicaDAO;
import br.com.perettis.schedula.model.SchedulaDAOFactory;
import br.com.perettis.schedula.model.Seguranca;
import br.com.perettis.schedula.model.UfDAO;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Transaction;
import org.jdesktop.application.Action;

/**
 *
 * @author  vinicius
 */
public class CadastroPessoaJuridica extends javax.swing.JDialog {

    PessoaJuridica pessoaJuridica;
    private PessoaJuridica ultimoCadastro;
    PessoaJuridicaDAO pessoaJuridicaDAO;
    private SchedulaDAOFactory daoFactory;
    Transaction t;
    org.jdesktop.application.ResourceMap resourceMap;
    FormSearch<Long, PessoaJuridica, PessoaJuridicaDAO> pesquisa;
    
    //TODO CPF E CNPJ ZEROS A ESQUERDA
    
    
    /** Creates new form CadastroPessoaJuridicas */
    public CadastroPessoaJuridica(SchedulaDAOFactory daoF) {
        setDaoFactory(daoF);
        initComponents();
        setModal(false);
        new OnEnterTab(getContentPane());
        ResetaForm();
        resourceMap = org.jdesktop.application.Application.getInstance(
                br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroPessoaJuridica.class);
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabDados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoEmpresa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSocios = new javax.swing.JTextArea();
        tabDocumentos = new javax.swing.JPanel();
        lCNPJ = new javax.swing.JLabel();
        lIE = new javax.swing.JLabel();
        lIM = new javax.swing.JLabel();
        lOAB = new javax.swing.JLabel();
        lOABUF = new javax.swing.JLabel();
        txtInscEstadual = new javax.swing.JTextField();
        txtInscMunicipal = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JFormattedTextField();
        tabEndereco = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        cbUf = new javax.swing.JComboBox();
        txtCep = new javax.swing.JFormattedTextField();
        tabContatos = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtFone1 = new javax.swing.JTextField();
        txtFone2 = new javax.swing.JTextField();
        txtFone3 = new javax.swing.JTextField();
        txtContato1 = new javax.swing.JTextField();
        txtContato2 = new javax.swing.JTextField();
        txtContato3 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        tabObservacao = new javax.swing.JPanel();
        sclObservacao = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroPessoaJuridica.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImage(new Imagens().getIcone());
        setName("Form"); // NOI18N

        txtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId.setName("txtId"); // NOI18N
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });

        txtNome.setName("txtNome"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        tabDados.setName("tabDados"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        txtCodigoEmpresa.setName("txtCodigoEmpresa"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtSocios.setColumns(20);
        txtSocios.setRows(5);
        txtSocios.setName("txtSocios"); // NOI18N
        jScrollPane1.setViewportView(txtSocios);

        javax.swing.GroupLayout tabDadosLayout = new javax.swing.GroupLayout(tabDados);
        tabDados.setLayout(tabDadosLayout);
        tabDadosLayout.setHorizontalGroup(
            tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDadosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabDadosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        tabDadosLayout.setVerticalGroup(
            tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDadosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("tabDados.TabConstraints.tabTitle"), tabDados); // NOI18N

        tabDocumentos.setName("tabDocumentos"); // NOI18N

        lCNPJ.setText(resourceMap.getString("lCNPJ.text")); // NOI18N
        lCNPJ.setName("lCNPJ"); // NOI18N

        lIE.setText(resourceMap.getString("lIE.text")); // NOI18N
        lIE.setName("lIE"); // NOI18N

        lIM.setText(resourceMap.getString("lIM.text")); // NOI18N
        lIM.setName("lIM"); // NOI18N

        lOAB.setName("lOAB"); // NOI18N

        lOABUF.setName("lOABUF"); // NOI18N

        txtInscEstadual.setName("txtInscEstadual"); // NOI18N

        txtInscMunicipal.setName("txtInscMunicipal"); // NOI18N

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.setName("txtCnpj"); // NOI18N

        javax.swing.GroupLayout tabDocumentosLayout = new javax.swing.GroupLayout(tabDocumentos);
        tabDocumentos.setLayout(tabDocumentosLayout);
        tabDocumentosLayout.setHorizontalGroup(
            tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDocumentosLayout.createSequentialGroup()
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDocumentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lIM))
                    .addGroup(tabDocumentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lIE))
                    .addGroup(tabDocumentosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lCNPJ)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInscEstadual, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtInscMunicipal, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(222, 222, 222))
            .addGroup(tabDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lOAB)
                .addGap(180, 180, 180)
                .addComponent(lOABUF)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        tabDocumentosLayout.setVerticalGroup(
            tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCNPJ)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lIE)
                    .addComponent(txtInscEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lIM)
                    .addComponent(txtInscMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lOAB)
                    .addComponent(lOABUF))
                .addGap(143, 143, 143))
        );

        new GetsDocument().setMaxLenght(100, txtInscEstadual);
        new GetsDocument().setMaxLenght(20, txtInscMunicipal);

        jTabbedPane1.addTab(resourceMap.getString("tabDocumentos.TabConstraints.tabTitle"), tabDocumentos); // NOI18N

        tabEndereco.setName("tabEndereco"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        txtEndereco.setName("txtEndereco"); // NOI18N

        txtBairro.setName("txtBairro"); // NOI18N

        txtCidade.setName("txtCidade"); // NOI18N

        cbUf.setName("cbUf"); // NOI18N

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setName("txtCep"); // NOI18N

        javax.swing.GroupLayout tabEnderecoLayout = new javax.swing.GroupLayout(tabEndereco);
        tabEndereco.setLayout(tabEnderecoLayout);
        tabEnderecoLayout.setHorizontalGroup(
            tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbUf, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCidade, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        tabEnderecoLayout.setVerticalGroup(
            tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEnderecoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        new GetsDocument().setMaxLenght(255, txtEndereco);
        new GetsDocument().setMaxLenght(255, txtBairro);
        new GetsDocument().setMaxLenght(100, txtCidade);
        cbUfMonta();

        jTabbedPane1.addTab(resourceMap.getString("tabEndereco.TabConstraints.tabTitle"), tabEndereco); // NOI18N

        tabContatos.setName("tabContatos"); // NOI18N

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        txtFone1.setName("txtFone1"); // NOI18N

        txtFone2.setName("txtFone2"); // NOI18N

        txtFone3.setName("txtFone3"); // NOI18N

        txtContato1.setName("txtContato1"); // NOI18N

        txtContato2.setName("txtContato2"); // NOI18N

        txtContato3.setName("txtContato3"); // NOI18N

        txtEmail.setName("txtEmail"); // NOI18N

        javax.swing.GroupLayout tabContatosLayout = new javax.swing.GroupLayout(tabContatos);
        tabContatos.setLayout(tabContatosLayout);
        tabContatosLayout.setHorizontalGroup(
            tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabContatosLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
                    .addGroup(tabContatosLayout.createSequentialGroup()
                        .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFone3)
                            .addComponent(txtFone2)
                            .addComponent(txtFone1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabContatosLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContato2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                            .addGroup(tabContatosLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContato3, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                            .addGroup(tabContatosLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContato1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        tabContatosLayout.setVerticalGroup(
            tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(txtFone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(txtFone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(txtFone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(tabContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        new GetsDocument().setMaxLenght(20, txtFone1);
        new GetsDocument().setMaxLenght(20, txtFone2);
        new GetsDocument().setMaxLenght(20, txtFone3);
        new GetsDocument().setMaxLenght(20, txtContato1);
        new GetsDocument().setMaxLenght(20, txtContato2);
        new GetsDocument().setMaxLenght(20, txtContato3);
        new GetsDocument().setMaxLenght(255, txtEmail);

        jTabbedPane1.addTab(resourceMap.getString("tabContatos.TabConstraints.tabTitle"), tabContatos); // NOI18N

        tabObservacao.setName("tabObservacao"); // NOI18N

        sclObservacao.setName("sclObservacao"); // NOI18N

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        txtObservacao.setName("txtObservacao"); // NOI18N
        sclObservacao.setViewportView(txtObservacao);

        javax.swing.GroupLayout tabObservacaoLayout = new javax.swing.GroupLayout(tabObservacao);
        tabObservacao.setLayout(tabObservacaoLayout);
        tabObservacaoLayout.setHorizontalGroup(
            tabObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(tabObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabObservacaoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sclObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        tabObservacaoLayout.setVerticalGroup(
            tabObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
            .addGroup(tabObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabObservacaoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sclObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab(resourceMap.getString("tabObservacao.TabConstraints.tabTitle"), tabObservacao); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getActionMap(CadastroPessoaJuridica.class, this);
        btnSalvar.setAction(actionMap.get("Salvar")); // NOI18N
        btnSalvar.setName("btnSalvar"); // NOI18N

        btnCancelar.setAction(actionMap.get("Cancelar")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        btnExcluir.setAction(actionMap.get("Excluir")); // NOI18N
        btnExcluir.setName("btnExcluir"); // NOI18N

        btnNovo.setAction(actionMap.get("Novo")); // NOI18N
        btnNovo.setName("btnNovo"); // NOI18N

        btnPesquisar.setAction(actionMap.get("Pesquisar")); // NOI18N
        btnPesquisar.setName("btnPesquisar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar))
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnNovo)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );

        new NumericDocument().setMaxLenght(12,txtId);
        GetsDocument gdNome = new GetsDocument();
        gdNome.setMaxLenght(100);
        txtNome.setDocument(gdNome);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-538)/2, (screenSize.height-512)/2, 538, 512);
    }// </editor-fold>//GEN-END:initComponents

private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
    if (!txtId.getText().equalsIgnoreCase("")) {
        Alterar();
    }
}//GEN-LAST:event_txtIdFocusLost

private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_F10) {
        Pesquisar();
    }
}//GEN-LAST:event_txtIdKeyPressed


    /**
     * Reinicia formulário
     */
  	public void ResetaForm() {
		txtId.setText("");
        txtBairro.setText("");
        txtInscMunicipal.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtCodigoEmpresa.setText("");
        txtContato1.setText("");
        txtContato2.setText("");
        txtContato3.setText("");
        txtCnpj.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtFone1.setText("");
        txtFone2.setText("");
        txtFone3.setText("");
        txtNome.setText("");
        txtObservacao.setText("");
        txtInscEstadual.setText("");
        cbUf.setSelectedIndex(-1);
        txtSocios.setText("");
        
        
        jTabbedPane1.setSelectedIndex(0);
        txtId.setEnabled(true);
		txtId.requestFocus();
		btnSalvar.setEnabled(false);
		btnExcluir.setEnabled(false);
	}

    @Action
    /**
     * Abre tela de pesquisa
     */
    public void Pesquisar(){
        if (pesquisa == null) {
            pesquisa = new PesquisaPessoaJuridica(getDaoFactory());
        }
        
        pesquisa.setTitle("Selecione a Pessoa Jurídica para Alteração.");
        pesquisa.doSearch();
        pesquisa.openSearch();
        PessoaJuridica vem = pesquisa.getEntity();
        if (vem != null){
            txtId.setText(String.valueOf(vem.getId()));
            Alterar();
        }
    }
    

    @Action
    /**
     * Prepara formulário para novo cadastro
     */
	public void Novo() {
		ResetaForm();
		txtId.setEnabled(false);
		pessoaJuridica = new PessoaJuridica();
		pessoaJuridicaDAO = daoFactory.getPessoaJuridicaDAO();
		btnSalvar.setEnabled(true);
	}
        
    @Action
    /**
     * Salva novo cadastro ou altera
     */
	public void Salvar() {

        // se id for nulo trata como inclusão
		if (pessoaJuridica.getId() == null) {

            if (!Seguranca.Permitido("Cadastro-PessoaJuridica-inclusao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }
            
            pessoaJuridica = new PessoaJuridica();
			t = pessoaJuridicaDAO.getSession().beginTransaction();
			t.begin();
			try {

				// Preenche dado nos objetos
                pessoaJuridica.setBairro(txtBairro.getText());
                
                               
                pessoaJuridica.setCep(txtCep.getText());
                pessoaJuridica.setCidade(txtCidade.getText());
                pessoaJuridica.setCodigoEmpresa(txtCodigoEmpresa.getText());
                pessoaJuridica.setContato1(txtContato1.getText());
                pessoaJuridica.setContato2(txtContato2.getText());
                pessoaJuridica.setContato3(txtContato3.getText());                

                if (!Filters.onlyNumbers(txtCnpj.getText()).equalsIgnoreCase("")) {
                    if (!DocumentsBR.CNPJ(txtCnpj.getText())) {
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.cnpj",
                                String.valueOf(txtCnpj.getText())));
                        txtCnpj.requestFocus();
                        return;
                    }
                    //Verifica se já existe mesmo cnpj
                    if (pessoaJuridicaDAO.buscaPorCnpj(Filters.onlyNumbers(txtCnpj.getText())) != null) {
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("jaexiste.cnpj",
                                String.valueOf(txtCnpj.getText())));
                        txtCnpj.requestFocus();
                        return;
                    }
                    pessoaJuridica.setCnpj(Filters.onlyNumbers(txtCnpj.getText()));
                }else{
                    pessoaJuridica.setCnpj(null);
                }

                
                //TODO ARRUMAR FOCOS DO ERRO DO EMAIL
                //TODO CONTINUAR COM TROCAS PARA PESSOA JURIDICA
                if ((txtEmail.getText().length() > 0)&& (!Email.validSintax(txtEmail.getText()))){
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.email", txtEmail.getText()));
                        txtEmail.requestFocus();
                        return;                    
                }
                pessoaJuridica.setEmail(txtEmail.getText());
                pessoaJuridica.setEndereco(txtEndereco.getText());
                pessoaJuridica.setFone1(txtFone1.getText());
                pessoaJuridica.setFone2(txtFone2.getText());
                pessoaJuridica.setFone3(txtFone3.getText());
                
                if(txtNome.getText().length() <=0){
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.nome",txtNome.getText()));
                        txtNome.requestFocus();
                        return;                    
                }
                pessoaJuridica.setNome(txtNome.getText());
                
                pessoaJuridica.setObservacao(txtObservacao.getText());

                
                if (!txtInscEstadual.getText().equalsIgnoreCase("")) {
                    pessoaJuridica.setInscEstadual(txtInscEstadual.getText());
                }else{
                    pessoaJuridica.setInscEstadual(null);
                }

                if (!txtInscMunicipal.getText().equalsIgnoreCase("")) {
                    pessoaJuridica.setInscMunicipal(txtInscMunicipal.getText());
                }else{
                    pessoaJuridica.setInscMunicipal(null);
                }

                
                pessoaJuridica.setUf((Uf) cbUf.getSelectedItem());

                pessoaJuridica.setSocios(txtSocios.getText());
                
                // Grava 
				pessoaJuridicaDAO.makePersistent(pessoaJuridica);
				t.commit();
                
                // Confirma
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.sucesso", 
						String.valueOf(pessoaJuridica.getId())));
                setUltimoCadastro(pessoaJuridica);
                
                // Reseta
                pessoaJuridica = null;
                ResetaForm();
			} catch (ExceptionInInitializerError e) {
                // Se ocorre algum erro, mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.erro") +
					e.getLocalizedMessage());
				t.rollback();
			}

		// Se for alteração
		} else {
         
            if (!Seguranca.Permitido("Cadastro-PessoaJuridica-alteracao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }
            
            try {
                // Preenche dado nos objetos
                pessoaJuridica.setBairro(txtBairro.getText());
                
                pessoaJuridica.setCep(txtCep.getText());
                pessoaJuridica.setCidade(txtCidade.getText());
                pessoaJuridica.setCodigoEmpresa(txtCodigoEmpresa.getText());
                pessoaJuridica.setContato1(txtContato1.getText());
                pessoaJuridica.setContato2(txtContato2.getText());
                pessoaJuridica.setContato3(txtContato3.getText());                

                if (!Filters.onlyNumbers(txtCnpj.getText()).equalsIgnoreCase("")) {
                    if (!DocumentsBR.CNPJ(txtCnpj.getText())) {
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.cnpj",
                                String.valueOf(txtCnpj.getText())));
                        txtCnpj.requestFocus();
                        return;
                    }
                    
                    
                    // Verifica se existe outro com mesmos dados
                    PessoaJuridica outro = pessoaJuridicaDAO.buscaPorCnpj(
                            Filters.onlyNumbers(txtCnpj.getText()));
                    if (outro != null) {
                        if (outro.getId() != pessoaJuridica.getId()) {

                            JOptionPane.showMessageDialog(this,
                                    resourceMap.getString("jaexiste.cnpj",
                                    String.valueOf(txtCnpj.getText())));
                            txtCnpj.requestFocus();
                            return;
                        }
                    }
                    pessoaJuridica.setCnpj(Filters.onlyNumbers(txtCnpj.getText()));
                } else {
                    pessoaJuridica.setCnpj(null);
                }

                if ((txtEmail.getText().length() > 0)&& (!Email.validSintax(txtEmail.getText()))){
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.email",txtEmail.getText()));
                        txtEmail.requestFocus();
                        return;                    
                }
                pessoaJuridica.setEmail(txtEmail.getText());

                pessoaJuridica.setEndereco(txtEndereco.getText());
                pessoaJuridica.setFone1(txtFone1.getText());
                pessoaJuridica.setFone2(txtFone2.getText());
                pessoaJuridica.setFone3(txtFone3.getText());
                
                if(txtNome.getText().length() <=0){
                        JOptionPane.showMessageDialog(
                                this,
                                resourceMap.getString("invalido.nome"));
                        txtNome.requestFocus();
                        return;                    
                }
                pessoaJuridica.setNome(txtNome.getText());
                
                pessoaJuridica.setObservacao(txtObservacao.getText());
                
                if (!txtInscEstadual.getText().equalsIgnoreCase("")) {
                    pessoaJuridica.setInscEstadual(txtInscEstadual.getText());
                }else{
                    pessoaJuridica.setInscEstadual(null);
                }

                if (!txtInscMunicipal.getText().equalsIgnoreCase("")) {
                    pessoaJuridica.setInscMunicipal(txtInscMunicipal.getText());
                }else{
                    pessoaJuridica.setInscMunicipal(null);
                }
                pessoaJuridica.setUf((Uf) cbUf.getSelectedItem());
                
                pessoaJuridica.setSocios(txtSocios.getText());
                
                // Grava alterações
				pessoaJuridicaDAO.makePersistent(pessoaJuridica);
				t.commit();
                
                // Mostra confirmação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.sucesso"));
                
                // Reinicia formulario
                pessoaJuridica = null;
				ResetaForm();

			} catch (Exception e) {
                // Qualquer erro mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.erro") +
                        e.getLocalizedMessage());
				t.rollback();
                e.printStackTrace();
			}
		}
	}

    /**
     * Abre cadastro no formulário para alteração
     */
	public void Alterar() {
        
        // Busca nova sessao
		pessoaJuridicaDAO = daoFactory.getPessoaJuridicaDAO();
		try {
            // Inicia transação
			t = pessoaJuridicaDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            pessoaJuridica = pessoaJuridicaDAO.findById(
                    Long.valueOf(txtId.getText()), true);
            
            // Preenche dados no formulário
            txtBairro.setText(pessoaJuridica.getBairro());
            txtCep.setText(pessoaJuridica.getCep());
            txtCidade.setText(pessoaJuridica.getCidade());
            txtCodigoEmpresa.setText(pessoaJuridica.getCodigoEmpresa());
            txtContato1.setText(pessoaJuridica.getContato1());
            txtContato2.setText(pessoaJuridica.getContato2());
            txtContato3.setText(pessoaJuridica.getContato3());
            if (pessoaJuridica.getCnpj()!=null) {
                txtCnpj.setText(pessoaJuridica.getCnpj());
            }else{
                txtCnpj.setText("");
            }
            txtEmail.setText(pessoaJuridica.getEmail());
            txtEndereco.setText(pessoaJuridica.getEndereco());
            txtFone1.setText(pessoaJuridica.getFone1());
            txtFone2.setText(pessoaJuridica.getFone2());
            txtFone3.setText(pessoaJuridica.getFone3());
            txtNome.setText(pessoaJuridica.getNome());
            txtObservacao.setText(pessoaJuridica.getObservacao());
            txtInscEstadual.setText(pessoaJuridica.getInscEstadual());
            txtInscMunicipal.setText(pessoaJuridica.getInscMunicipal());

            txtSocios.setText(pessoaJuridica.getSocios());
            cbUf.setSelectedItem(pessoaJuridica.getUf());
            
            
            // Ativa controles disponíveis
			btnSalvar.setEnabled(true);
			btnExcluir.setEnabled(true);
            txtId.setEnabled(false);

		} catch (Exception e) {
            e.printStackTrace();
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("altera.errobusca", txtId.getText()));
			txtId.setEnabled(true);
			btnSalvar.setEnabled(false);
			btnExcluir.setEnabled(false);
			txtId.requestFocus();
		}
	}
    
    @Action
    /**
     * Limpa formulário, cancelando edição atual
     */
	public void Cancelar() {
		pessoaJuridica = null;
		ResetaForm();
	}
	
	@Action
    /**
     * Exclui objeto atual
     */
	public void Excluir() {
        
        if (!Seguranca.Permitido("Cadastro-PessoaJuridica-exclusao")) {
            JOptionPane.showMessageDialog(null, "Sem permissão");
            return;
        }
        
		// Solicita confirmação
        int opcao = JOptionPane.showConfirmDialog(this,
                resourceMap.getString("exclui.confirmacao"),
                resourceMap.getString("exclui.confirmacao.titulo"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        switch (opcao) {
			case 0: // Resposta sim
				try {
                    // Remove da persistencia
					pessoaJuridicaDAO.makeTransient(pessoaJuridica);
					t.commit();
                    // Confirma
					JOptionPane.showMessageDialog(this,
						resourceMap.getString("exclui.ok"));
                    // Limpa form
					pessoaJuridica = null;
					ResetaForm();

				} catch (Exception e) {
                    // Dando erro diz que não é possivel
					JOptionPane.showMessageDialog(this,
						resourceMap.getString(
						"exclui.naopode"));
				}
				break;
			case 1: // Resposta não
				break;
		}

	}

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.ButtonGroup bgSexo;
    javax.swing.JButton btnCancelar;
    javax.swing.JButton btnExcluir;
    javax.swing.JButton btnNovo;
    javax.swing.JButton btnPesquisar;
    javax.swing.JButton btnSalvar;
    javax.swing.JComboBox cbUf;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel16;
    javax.swing.JLabel jLabel17;
    javax.swing.JLabel jLabel18;
    javax.swing.JLabel jLabel19;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel20;
    javax.swing.JLabel jLabel21;
    javax.swing.JLabel jLabel22;
    javax.swing.JLabel jLabel23;
    javax.swing.JLabel jLabel24;
    javax.swing.JLabel jLabel25;
    javax.swing.JLabel jLabel26;
    javax.swing.JLabel jLabel27;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTabbedPane jTabbedPane1;
    javax.swing.JLabel lCNPJ;
    javax.swing.JLabel lIE;
    javax.swing.JLabel lIM;
    javax.swing.JLabel lOAB;
    javax.swing.JLabel lOABUF;
    javax.swing.JScrollPane sclObservacao;
    javax.swing.JPanel tabContatos;
    javax.swing.JPanel tabDados;
    javax.swing.JPanel tabDocumentos;
    javax.swing.JPanel tabEndereco;
    javax.swing.JPanel tabObservacao;
    javax.swing.JTextField txtBairro;
    javax.swing.JFormattedTextField txtCep;
    javax.swing.JTextField txtCidade;
    javax.swing.JFormattedTextField txtCnpj;
    javax.swing.JTextField txtCodigoEmpresa;
    javax.swing.JTextField txtContato1;
    javax.swing.JTextField txtContato2;
    javax.swing.JTextField txtContato3;
    javax.swing.JTextField txtEmail;
    javax.swing.JTextField txtEndereco;
    javax.swing.JTextField txtFone1;
    javax.swing.JTextField txtFone2;
    javax.swing.JTextField txtFone3;
    javax.swing.JTextField txtId;
    javax.swing.JTextField txtInscEstadual;
    javax.swing.JTextField txtInscMunicipal;
    javax.swing.JTextField txtNome;
    javax.swing.JTextArea txtObservacao;
    javax.swing.JTextArea txtSocios;
    // End of variables declaration//GEN-END:variables
  
   
    private void cbUfMonta() {
        UfDAO ufDAO =  getDaoFactory().getUfDAO();
        Transaction tuf = ufDAO.getSession().getTransaction();
        tuf.begin();
        List<Uf> list = ufDAO.findAll();
        Iterator<Uf> it = list.iterator();
        while (it.hasNext()) {
            cbUf.addItem(it.next());
        }
    }

    public

    SchedulaDAOFactory getDaoFactory() {
        return daoFactory;
    }

    public void setDaoFactory(SchedulaDAOFactory daoFactory) {
        this.daoFactory = daoFactory;
    }

    public PessoaJuridica getUltimoCadastro() {
        return ultimoCadastro;
    }

    public void setUltimoCadastro(PessoaJuridica ultimoCadastro) {
        this.ultimoCadastro = ultimoCadastro;
    }
}

