/*
 * CadastroEstadoCivil.java
 *
 * Created on May 27, 2008, 9:09 PM
 */
package br.com.perettis.schedula;

import br.com.perettis.gets.dao.DAOConstants;
import br.com.perettis.gets.swing.FormSearch;
import br.com.perettis.gets.swing.NumericDocument;
import br.com.perettis.gets.swing.GetsDocument;
import br.com.perettis.gets.dao.DAOFactoryAbstract;
import br.com.perettis.gets.swing.FormSearchColumn;
import br.com.perettis.gets.text.BooleanFormat;
import br.com.perettis.schedula.entity.SchedulaRotina;
import br.com.perettis.schedula.entity.Usuario;
import br.com.perettis.schedula.entity.UsuarioDireito;
import br.com.perettis.schedula.model.SchedulaDAOFactory;
import br.com.perettis.schedula.model.SchedulaRotinaDAO;
import br.com.perettis.schedula.model.Seguranca;
import br.com.perettis.schedula.model.UsuarioDAO;
import br.com.perettis.schedula.model.UsuarioDireitoDAO;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import org.hibernate.Transaction;
import org.jdesktop.application.Action;

/**
 *
 * @author  Vinicius Peretti
 * 
 * 
 */
public class CadastroUsuarioHabilitacoes extends javax.swing.JFrame {

    Usuario usuario;
    UsuarioDAO UsuarioDAO;
    private SchedulaDAOFactory daoFactory;
    Transaction t;
    org.jdesktop.application.ResourceMap resourceMap;
    FormSearch<Long, Usuario, UsuarioDAO> pesquisa;
    DefaultListModel lmDireitos = new DefaultListModel();

    /** Creates new form CadastroEstadoCivil */
    public CadastroUsuarioHabilitacoes(SchedulaDAOFactory daoFactory) {
        setDaoFactory(daoFactory);
        initComponents();
        ResetaForm();
        resourceMap = org.jdesktop.application.Application.getInstance(
                br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroUsuarioHabilitacoes.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alerta = new javax.swing.JOptionPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpDados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbDesabilitado = new javax.swing.JCheckBox();
        cbAdministrador = new javax.swing.JCheckBox();
        txtSenha = new javax.swing.JPasswordField();
        txtNome = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JFormattedTextField();
        jpHab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDireitos = new javax.swing.JList();
        cbRotinas = new javax.swing.JComboBox();
        btnAddHab = new javax.swing.JButton();
        btnRemHab = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        lApelido = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lCodigo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtId = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        txtApelido = new javax.swing.JFormattedTextField();

        alerta.setName("alerta"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroUsuarioHabilitacoes.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImage(new Imagens().getIcone());
        setName("Form"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jpDados.setName("jpDados"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        lNome.setText(resourceMap.getString("lNome.text")); // NOI18N
        lNome.setName("lNome"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        cbDesabilitado.setText(resourceMap.getString("cbDesabilitado.text")); // NOI18N
        cbDesabilitado.setName("cbDesabilitado"); // NOI18N

        cbAdministrador.setText(resourceMap.getString("cbAdministrador.text")); // NOI18N
        cbAdministrador.setName("cbAdministrador"); // NOI18N
        cbAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdministradorActionPerformed(evt);
            }
        });

        txtSenha.setText(resourceMap.getString("txtSenha.text")); // NOI18N
        txtSenha.setName("txtSenha"); // NOI18N

        txtNome.setText(resourceMap.getString("txtNome.text")); // NOI18N
        txtNome.setName("txtNome"); // NOI18N

        txtEmail.setText(resourceMap.getString("txtEmail.text")); // NOI18N
        txtEmail.setName("txtEmail"); // NOI18N

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lNome)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDesabilitado)
                            .addComponent(cbAdministrador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                .addGap(298, 298, 298))
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDesabilitado)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("jpDados.TabConstraints.tabTitle"), jpDados); // NOI18N

        jpHab.setName("jpHab"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lstDireitos.setModel(lmDireitos);
        lstDireitos.setName("lstDireitos"); // NOI18N
        jScrollPane1.setViewportView(lstDireitos);

        cbRotinas.setName("cbRotinas"); // NOI18N

        btnAddHab.setText(resourceMap.getString("btnAddHab.text")); // NOI18N
        btnAddHab.setName("btnAddHab"); // NOI18N
        btnAddHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHabActionPerformed(evt);
            }
        });

        btnRemHab.setText(resourceMap.getString("btnRemHab.text")); // NOI18N
        btnRemHab.setName("btnRemHab"); // NOI18N
        btnRemHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemHabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHabLayout = new javax.swing.GroupLayout(jpHab);
        jpHab.setLayout(jpHabLayout);
        jpHabLayout.setHorizontalGroup(
            jpHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHabLayout.createSequentialGroup()
                        .addComponent(btnAddHab, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemHab)
                        .addGap(399, 399, 399))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHabLayout.createSequentialGroup()
                        .addGroup(jpHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                            .addComponent(cbRotinas, 0, 624, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jpHabLayout.setVerticalGroup(
            jpHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbRotinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jpHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddHab)
                    .addComponent(btnRemHab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        cbRotinasMonta();

        jTabbedPane1.addTab(resourceMap.getString("jpHab.TabConstraints.tabTitle"), jpHab); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getActionMap(CadastroUsuarioHabilitacoes.class, this);
        btnNovo.setAction(actionMap.get("Novo")); // NOI18N
        btnNovo.setText(resourceMap.getString("btnNovo.text")); // NOI18N
        btnNovo.setName("btnNovo"); // NOI18N

        lApelido.setText(resourceMap.getString("lApelido.text")); // NOI18N
        lApelido.setName("lApelido"); // NOI18N

        btnExcluir.setAction(actionMap.get("Excluir")); // NOI18N
        btnExcluir.setText(resourceMap.getString("btnExcluir.text")); // NOI18N
        btnExcluir.setName("btnExcluir"); // NOI18N

        btnCancelar.setAction(actionMap.get("Cancelar")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        lCodigo.setText(resourceMap.getString("lCodigo.text")); // NOI18N
        lCodigo.setName("lCodigo"); // NOI18N

        btnSalvar.setAction(actionMap.get("Salvar")); // NOI18N
        btnSalvar.setText(resourceMap.getString("btnSalvar.text")); // NOI18N
        btnSalvar.setName("btnSalvar"); // NOI18N

        txtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId.setName("txtId"); // NOI18N
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        btnPesquisar.setAction(actionMap.get("Pesquisar")); // NOI18N
        btnPesquisar.setText(resourceMap.getString("btnPesquisar.text")); // NOI18N
        btnPesquisar.setName("btnPesquisar"); // NOI18N

        txtApelido.setName("txtApelido"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lApelido)
                            .addComponent(lCodigo))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar))
                            .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnPesquisar)
                    .addComponent(lCodigo)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lApelido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        NumericDocument gdId = new NumericDocument();
        gdId.setMaxLenght(6);
        txtId.setDocument(gdId);
        GetsDocument gdDescricao = new GetsDocument();
        gdDescricao.setMaxLenght(50);
        txtApelido.setDocument(gdDescricao);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-688)/2, (screenSize.height-428)/2, 688, 428);
    }// </editor-fold>//GEN-END:initComponents

private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
    if (!txtId.getText().equalsIgnoreCase("")) {
        Alterar();
    }
}//GEN-LAST:event_txtIdFocusLost

    @SuppressWarnings("static-access")
private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
}//GEN-LAST:event_txtIdKeyTyped

private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_F10) {
        Pesquisar();
    }
}//GEN-LAST:event_txtIdKeyPressed

private void btnAddHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHabActionPerformed
    UsuarioDireito usuarioDireito = new UsuarioDireito();
    usuarioDireito.setRotina((SchedulaRotina) cbRotinas.getSelectedItem());
    if ((usuario.getId() != null) && (usuario.getId() > 0)) {
        usuarioDireito.setUsuario(usuario);
    }
    if (!lmDireitos.isEmpty()) {
        Object[] aVer = lmDireitos.toArray();
        for (int i = 0; i < aVer.length; i++) {
            if (((UsuarioDireito) aVer[i]).getRotina().getId() == usuarioDireito.getRotina().getId()) {
                JOptionPane.showMessageDialog(this, "Usuário já possui direito sobre essa rotina");
                return;
            }
        }
    }
    lmDireitos.addElement(usuarioDireito);
}//GEN-LAST:event_btnAddHabActionPerformed

private void btnRemHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemHabActionPerformed
    int[] aToDel = lstDireitos.getSelectedIndices();

    for (int i = 0; i < aToDel.length; i++) {
        lmDireitos.removeElementAt(aToDel[i] - i);
    }

    if (usuario.getId() > 0) {
        Object[] aDireitos = lstDireitos.getSelectedValues();
        for (int i = 0; i < aDireitos.length; i++) {
            usuario.getDireitos().remove(aDireitos[i]);
        }
    }
}//GEN-LAST:event_btnRemHabActionPerformed

private void cbAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAdministradorActionPerformed
    if (cbAdministrador.isSelected()) {
        jTabbedPane1.setEnabledAt(1, false);
    } else {
        jTabbedPane1.setEnabledAt(1, true);
    }
}//GEN-LAST:event_cbAdministradorActionPerformed

	

    private void cbRotinasMonta() {
        SchedulaRotinaDAO schedulaRotinaDAO =  getDaoFactory().getSchedulaRotinaDAO();
        Transaction t = schedulaRotinaDAO.getSession().getTransaction();
        t.begin();
        //List<SchedulaRotina> esList = schedulaRotinaDAO.findByPropertyLike("desabilitado", false, DAOConstants.EQUAL, "nome");
        List<SchedulaRotina> esList = schedulaRotinaDAO.buscaLista();
        Iterator<SchedulaRotina> itEs = esList.iterator();
        while (itEs.hasNext()) {
            cbRotinas.addItem(itEs.next());
        }
    }
	
    
    /**
     * Reinicia formulário
     */
  	public void ResetaForm() {
		txtId.setText("");
		txtApelido.setText("");
        txtSenha.setText("");
        txtNome.setText("");
        txtEmail.setText("");
        cbAdministrador.setSelected(false);
		cbDesabilitado.setSelected(false);
		txtId.setEnabled(true);
		txtId.requestFocus();
		btnSalvar.setEnabled(false);
		btnExcluir.setEnabled(false);
        lmDireitos.removeAllElements();
        cbRotinas.setSelectedIndex(-1);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(0);
        
	}
    
    @Action
    /**
     * Abre tela de pesquisa
     */
    public void Pesquisar(){
        if (pesquisa == null) {
            pesquisa = new FormSearch();
            Set<FormSearchColumn> colunas = new LinkedHashSet<FormSearchColumn>();


            FormSearchColumn fscApelido = new FormSearchColumn();
            fscApelido.setProperty("apelido");
            fscApelido.setPropertyClass(String.class);
            fscApelido.setLabel("Apelido");
            fscApelido.setWidth(200);
            fscApelido.setAlign(SwingConstants.LEFT);
            fscApelido.setTypeSearch(DAOConstants.LIKE);
            colunas.add(fscApelido);

            FormSearchColumn fscNome = new FormSearchColumn();
            fscNome.setProperty("nome");
            fscNome.setPropertyClass(String.class);
            fscNome.setLabel("Nome");
            fscNome.setWidth(300);
            fscNome.setAlign(SwingConstants.LEFT);
            fscNome.setTypeSearch(DAOConstants.LIKE);
            colunas.add(fscNome);


            FormSearchColumn fscId = new FormSearchColumn();
            fscId.setProperty("id");
            fscId.setPropertyClass(Long.class);
            fscId.setLabel("ID");
            fscId.setWidth(100);
            fscId.setAlign(SwingConstants.RIGHT);
            fscId.setTypeSearch(DAOConstants.ABOVE_EQUAL);
            colunas.add(fscId);


            // Cria formatador da coluna desabilitado
            BooleanFormat desFormat = new BooleanFormat();
            desFormat.setTrueString("desabilitado");
            desFormat.setFalseString("habilitado");

            FormSearchColumn fscDesabilitado = new FormSearchColumn();
            fscDesabilitado.setProperty("desabilitado");
            fscDesabilitado.setPropertyClass(Boolean.class);
            fscDesabilitado.setLabel("Situação");
            fscDesabilitado.setWidth(10);
            fscDesabilitado.setAlign(SwingConstants.CENTER);
            fscDesabilitado.setTypeSearch(DAOConstants.EQUAL);
            fscDesabilitado.setFormatter(desFormat);
            colunas.add(fscDesabilitado);
            

            pesquisa.setIdProperty("id");
            pesquisa.setIdClass(Long.class);
            pesquisa.setColumns(colunas);
            pesquisa.setDefaultProperty("apelido");
            pesquisa.setEntityClass(Usuario.class);
            pesquisa.setDaoClass(UsuarioDAO.class);
            pesquisa.setDaoFactory((DAOFactoryAbstract) getDaoFactory());
            pesquisa.setTitle("Selecione o Usuário para Alteração.");
            pesquisa.makeForm();
            pesquisa.getRbAny().setSelected(true);
            //pesquisa.setKeySearch("teste");
            //pesquisa.doSearch();
        }
        
        pesquisa.doSearch();
        pesquisa.openSearch();
        Usuario vem = pesquisa.getEntity();
        if (vem != null){
            txtId.setText(String.valueOf(vem.getId()));
            Alterar();
        }
    }

	@Action
    /**
     * Prepara formulário para novo cadastro
     */
	public void Novo() {
		ResetaForm();
		txtId.setEnabled(false);
		usuario = new Usuario();
		UsuarioDAO = daoFactory.getUsuarioDAO();
		btnSalvar.setEnabled(true);
	}

	@Action
    /**
     * Salva novo cadastro ou altera
     */
	public void Salvar() {

        // se id for nulo trata como inclusão
		if (usuario.getId() == null) {
               
            if (!Seguranca.Permitido("Suporte-CadastroUsuario-inclusao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }
            
            usuario = new Usuario();
			t = UsuarioDAO.getSession().beginTransaction();
			t.begin();
			try {
                //Verifica se já existe mesma descrição
				if (UsuarioDAO.buscaPorApelido(txtApelido.getText())
						!= null) {
					JOptionPane.showMessageDialog(
						this,
						resourceMap.getString("jaexiste.apelido", 
							String.valueOf(txtApelido.getText())));
					txtApelido.requestFocus();
					return;
				}

				// Preenche dado nos objetos
				usuario.setApelido(txtApelido.getText());
                //TODO usar metodo getPassword, preciso converter char to byte
                if (!txtSenha.getText().equalsIgnoreCase("")){
                    usuario.setSenha(Seguranca.CriptografaSenha(txtSenha.getText()));
                }
                usuario.setNome(txtNome.getText());
                usuario.setEmail(txtEmail.getText());
                usuario.setAdministrador(cbAdministrador.isSelected());
				usuario.setDesabilitado(cbDesabilitado.isSelected());
                
                
              
                // Grava 
				UsuarioDAO.makePersistent(usuario);
				t.commit();

                
                
                UsuarioDireitoDAO usuarioDireitoDAO = daoFactory.getUsuarioDireitoDAO();
                t = usuarioDireitoDAO.getSession().getTransaction();
                t.begin();
                Object[] aDireitos = lmDireitos.toArray();
                for (int i = 0; i < aDireitos.length; i++) {
                    UsuarioDireito direito = (UsuarioDireito)aDireitos[i];
                    direito.setUsuario(usuario);
                    usuarioDireitoDAO.makePersistent(direito);
                }
                t.commit();
                
                
                // Confirma
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.sucesso", 
						String.valueOf(usuario.getId())));
                // Reseta
                usuario = null;
                ResetaForm();
			} catch (Exception e) {
                // Se ocorre algum erro, mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.erro") +
					e.getLocalizedMessage());
				t.rollback();
			}


		// Se for alteração
		} else {
            
            if (!Seguranca.Permitido("Suporte-CadastroUsuario-alteracao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }
            
            try {
                // Verifica se existe outro com mesmos dados
                Usuario outro = UsuarioDAO.buscaPorApelido(
                        txtApelido.getText());
                if (outro != null) {
                    if (outro.getId() != usuario.getId()) {

                        JOptionPane.showMessageDialog(this,
                                resourceMap.getString("jaexiste.apelido",
                                String.valueOf(txtApelido.getText())));
                        txtApelido.requestFocus();
                        return;
                    }
                }

				// Preenche dados do form no objeto
				usuario.setApelido(txtApelido.getText());
                //TODO usar metodo getPassword, preciso converter char to byte
                if (!txtSenha.getText().equalsIgnoreCase("")){
                    usuario.setSenha(Seguranca.CriptografaSenha(txtSenha.getText()));
                }
                usuario.setNome(txtNome.getText());
                usuario.setEmail(txtEmail.getText());
                usuario.setAdministrador(cbAdministrador.isSelected());
				usuario.setDesabilitado(cbDesabilitado.isSelected());


                
                Set<UsuarioDireito> direitos = new LinkedHashSet<UsuarioDireito>();// = usuario.getDireitos();
                direitos.clear();
                Object[] aDireitos = lmDireitos.toArray();
                for (int i = 0; i < aDireitos.length; i++) {
                    direitos.add((UsuarioDireito)aDireitos[i]);
                    //usuarioDireitoDAO.makePersistent(direito);
                }
                usuario.setDireitos(direitos);
                
                // Grava alterações
				UsuarioDAO.makePersistent(usuario);
				t.commit();
                

                
                // Mostra confirmação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.sucesso"));
                
                // Reinicia formulario
                usuario = null;
				ResetaForm();

			} catch (Exception e) {
                // Qualquer erro mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.erro") +
                        e.getLocalizedMessage());
				t.rollback();
			}
		}
	}

    /**
     * Abre cadastro no formulário para alteração
     */
	public void Alterar() {
        // Busca nova sessao
		UsuarioDAO = daoFactory.getUsuarioDAO();
		try {
            // Inicia transação
			t = UsuarioDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            usuario = UsuarioDAO.findById(
                    Long.valueOf(txtId.getText()), true);
            
            // Preenche dados no formulário
            txtApelido.setText(usuario.getApelido());
            txtNome.setText(usuario.getNome());
            txtEmail.setText(usuario.getEmail());
            cbAdministrador.setSelected(usuario.isAdministrador());
            jTabbedPane1.setEnabledAt(1, !usuario.isAdministrador());
            
            cbDesabilitado.setSelected(usuario.isDesabilitado());
            
            Set<UsuarioDireito> direitos = usuario.getDireitos();
            for (UsuarioDireito usuarioDireito : direitos) {
                lmDireitos.addElement(usuarioDireito);
            }
            // Ativa controles disponíveis
			btnSalvar.setEnabled(true);
			btnExcluir.setEnabled(true);
            txtId.setEnabled(false);
            jTabbedPane1.setSelectedIndex(0);

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("altera.errobusca", txtId.getText()));
			txtId.setEnabled(true);
			btnSalvar.setEnabled(false);
			btnExcluir.setEnabled(false);
			txtId.requestFocus();
		}
	}

	@Action
    /**
     * Limpa formulário, cancelando edição atual
     */
	public void Cancelar() {
		usuario = null;
		ResetaForm();
	}
	
	@Action
    /**
     * Exclui objeto atual
     */
	public void Excluir() {
        
        if (!Seguranca.Permitido("Suporte-CadastroUsuario-exclusao")) {
            JOptionPane.showMessageDialog(null, "Sem permissão");
            return;
        }
                
		// Solicita confirmação
        int opcao = JOptionPane.showConfirmDialog(this,
                resourceMap.getString("exclui.confirmacao"),
                resourceMap.getString("exclui.confirmacao.titulo"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        switch (opcao) {
			case 0: // Resposta sim
				try {
                    // Remove da persistencia
					UsuarioDAO.makeTransient(usuario);
					t.commit();
                    // Confirma
					JOptionPane.showMessageDialog(this,
						resourceMap.getString("exclui.ok"));
                    // Limpa form
					usuario = null;
					ResetaForm();

				} catch (Exception e) {
                    // Dando erro diz que não é possivel
					JOptionPane.showMessageDialog(this,
						resourceMap.getString(
						"exclui.naopode"));
				}
				break;
			case 1: // Resposta não
				break;
		}

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alerta;
    private javax.swing.JButton btnAddHab;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemHab;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox cbAdministrador;
    private javax.swing.JCheckBox cbDesabilitado;
    private javax.swing.JComboBox cbRotinas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpHab;
    private javax.swing.JLabel lApelido;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lNome;
    private javax.swing.JList lstDireitos;
    private javax.swing.JFormattedTextField txtApelido;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JFormattedTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

	public SchedulaDAOFactory getDaoFactory() {
		return daoFactory;
	}

	public void setDaoFactory(SchedulaDAOFactory daoFactory) {
		this.daoFactory = daoFactory;
	}

}
