/*
 * CadastroEstadoCivil.java
 *
 * Created on May 27, 2008, 9:09 PM
 */
package br.com.perettis.schedula;

import br.com.perettis.gets.swing.FormSearch;
import br.com.perettis.gets.swing.NumericDocument;
import br.com.perettis.gets.swing.GetsDocument;
import br.com.perettis.schedula.entity.Acompanhamento;
import br.com.perettis.schedula.entity.AcompanhamentoTipo;
import br.com.perettis.schedula.entity.AcordoParcela;
import br.com.perettis.schedula.entity.Advogado;
import br.com.perettis.schedula.entity.AudienciaTipo;
import br.com.perettis.schedula.entity.Pessoa;
import br.com.perettis.schedula.entity.Processo;
import br.com.perettis.schedula.entity.Vara;
import br.com.perettis.schedula.model.AcompanhamentoDAO;
import br.com.perettis.schedula.model.AcompanhamentoTipoDAO;
import br.com.perettis.schedula.model.AcordoParcelaDAO;
import br.com.perettis.schedula.model.AdvogadoDAO;
import br.com.perettis.schedula.model.AudienciaTipoDAO;
import br.com.perettis.schedula.model.PessoaDAO;
import br.com.perettis.schedula.model.SchedulaDAOFactory;
import br.com.perettis.schedula.model.ProcessoDAO;
import br.com.perettis.schedula.model.Seguranca;
import br.com.perettis.schedula.model.VaraDAO;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Transaction;
import org.jdesktop.application.Action;

/**
 *
 * @author  Vinicius Peretti
 * 
 * 
 */
public class CadastroAndamentoProcesso extends javax.swing.JFrame {

    Processo processo;
    Acompanhamento acompanhamento;
    ProcessoDAO processoDAO;
    AcompanhamentoDAO acompanhamentoDAO;
    private SchedulaDAOFactory daoFactory;
    Transaction t;
    org.jdesktop.application.ResourceMap resourceMap;
    FormSearch<Long, Processo, ProcessoDAO> pesquisa;
    FormSearch<Integer, Vara, VaraDAO> pesquisaVara;
    Pessoa cliente, contraria;
    Advogado advogado;
    Vara vara;
    SimpleDateFormat formataHora = new SimpleDateFormat("HH:mm");
    SimpleDateFormat formataData = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat formataDataHora = new SimpleDateFormat("yyyy-MM-dd HH:mm");
    NumberFormat formataParcela = NumberFormat.getInstance(new Locale("pt", "BR"));
    Set<AcordoParcela> acordoParcelas = new LinkedHashSet<AcordoParcela>();

    /** Creates new form CadastroEstadoCivil */
    public CadastroAndamentoProcesso(SchedulaDAOFactory daoFactory) {
        setDaoFactory(daoFactory);
        initComponents();
        cbAcompanhamentoTipoMonta();
        cbAudienciaTipoMonta();
        ResetaForm();
        resourceMap = org.jdesktop.application.Application.getInstance(
                br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroAndamentoProcesso.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alerta = new javax.swing.JOptionPane();
        bgTipoAndamento = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpDados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdAdvogado = new javax.swing.JTextField();
        txtNomeAdvogado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtNomeContraria = new javax.swing.JTextField();
        txtIdContraria = new javax.swing.JTextField();
        txtAdvogadoContraria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        jpDetalhes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbAndamentos = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        lNumProcesso = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lCodigo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtId = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        txtNumeroProcesso = new javax.swing.JFormattedTextField();
        lVara = new javax.swing.JLabel();
        txtIdVara = new javax.swing.JTextField();
        txtVaraNome = new javax.swing.JTextField();
        btnPesqVara = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbBaixa = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtDataCadastro = new org.jdesktop.swingx.JXDatePicker();
        txtDataProvidencia = new org.jdesktop.swingx.JXDatePicker();
        txtDataBaixa = new org.jdesktop.swingx.JXDatePicker();
        txtHoraProvidencia = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        cbAcompanhamentoTipo = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        cbAudienciaTipo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbAcordoParcelas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtParcelaValor = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtVencimento = new org.jdesktop.swingx.JXDatePicker();
        btnIncluirParcela = new javax.swing.JButton();
        btnMudarProcesso = new javax.swing.JButton();

        alerta.setName("alerta"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroAndamentoProcesso.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImage(new Imagens().getIcone());
        setName("Form"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jpDados.setName("jpDados"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        txtIdAdvogado.setEditable(false);
        txtIdAdvogado.setText(resourceMap.getString("txtIdAdvogado.text")); // NOI18N
        txtIdAdvogado.setName("txtIdAdvogado"); // NOI18N
        txtIdAdvogado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdAdvogadoFocusLost(evt);
            }
        });

        txtNomeAdvogado.setEditable(false);
        txtNomeAdvogado.setText(resourceMap.getString("txtNomeAdvogado.text")); // NOI18N
        txtNomeAdvogado.setName("txtNomeAdvogado"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        txtNomeContraria.setEditable(false);
        txtNomeContraria.setName("txtNomeContraria"); // NOI18N

        txtIdContraria.setEditable(false);
        txtIdContraria.setName("txtIdContraria"); // NOI18N
        txtIdContraria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdContrariaFocusLost(evt);
            }
        });

        txtAdvogadoContraria.setText(resourceMap.getString("txtAdvogadoContraria.text")); // NOI18N
        txtAdvogadoContraria.setName("txtAdvogadoContraria"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdContraria, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeContraria, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdvogadoContraria, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtIdContraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeContraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtAdvogadoContraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NumericDocument gdIdContraria = new NumericDocument();
        gdIdContraria.setMaxLenght(12);
        txtIdContraria.setDocument(gdIdContraria);
        new GetsDocument().setMaxLenght(100, txtAdvogadoContraria);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        txtIdCliente.setEditable(false);
        txtIdCliente.setName("txtIdCliente"); // NOI18N
        txtIdCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdClienteFocusLost(evt);
            }
        });

        txtNomeCliente.setEditable(false);
        txtNomeCliente.setName("txtNomeCliente"); // NOI18N

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeCliente)
                            .addComponent(txtNomeAdvogado, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
        );

        NumericDocument gdIdAdvogado = new NumericDocument();
        gdIdAdvogado.setMaxLenght(12);
        txtIdAdvogado.setDocument(gdIdAdvogado);
        NumericDocument gdIdCliente = new NumericDocument();
        gdIdCliente.setMaxLenght(12);
        txtIdCliente.setDocument(gdIdCliente);

        jTabbedPane1.addTab(resourceMap.getString("jpDados.TabConstraints.tabTitle"), jpDados); // NOI18N

        jpDetalhes.setName("jpDetalhes"); // NOI18N
        jpDetalhes.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jtbAndamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data Compromisso", "Tipo", "Audiência", "Cadastro", "Obs", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbAndamentos.setName("jtbAndamentos"); // NOI18N
        jtbAndamentos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbAndamentos.setAutoCreateRowSorter(true);
        jtbAndamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbAndamentosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtbAndamentos);

        jpDetalhes.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab(resourceMap.getString("jpDetalhes.TabConstraints.tabTitle"), jpDetalhes); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getActionMap(CadastroAndamentoProcesso.class, this);
        btnNovo.setAction(actionMap.get("Novo")); // NOI18N
        btnNovo.setText(resourceMap.getString("btnNovo.text")); // NOI18N
        btnNovo.setName("btnNovo"); // NOI18N

        lNumProcesso.setText(resourceMap.getString("lNumProcesso.text")); // NOI18N
        lNumProcesso.setName("lNumProcesso"); // NOI18N

        btnExcluir.setAction(actionMap.get("Excluir")); // NOI18N
        btnExcluir.setText(resourceMap.getString("btnExcluir.text")); // NOI18N
        btnExcluir.setName("btnExcluir"); // NOI18N

        btnCancelar.setAction(actionMap.get("Cancelar")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        lCodigo.setText(resourceMap.getString("lCodigo.text")); // NOI18N
        lCodigo.setName("lCodigo"); // NOI18N

        btnSalvar.setAction(actionMap.get("Salvar")); // NOI18N
        btnSalvar.setText(resourceMap.getString("btnSalvar.text")); // NOI18N
        btnSalvar.setName("btnSalvar"); // NOI18N

        txtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId.setName("txtId"); // NOI18N
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        btnPesquisar.setAction(actionMap.get("Pesquisar")); // NOI18N
        btnPesquisar.setText(resourceMap.getString("btnPesquisar.text")); // NOI18N
        btnPesquisar.setName("btnPesquisar"); // NOI18N

        txtNumeroProcesso.setName("txtNumeroProcesso"); // NOI18N
        txtNumeroProcesso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroProcessoFocusLost(evt);
            }
        });

        lVara.setText(resourceMap.getString("lVara.text")); // NOI18N
        lVara.setName("lVara"); // NOI18N

        txtIdVara.setText(resourceMap.getString("txtIdVara.text")); // NOI18N
        txtIdVara.setName("txtIdVara"); // NOI18N
        txtIdVara.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdVaraFocusLost(evt);
            }
        });

        txtVaraNome.setEditable(false);
        txtVaraNome.setText(resourceMap.getString("txtVaraNome.text")); // NOI18N
        txtVaraNome.setName("txtVaraNome"); // NOI18N

        btnPesqVara.setText(resourceMap.getString("btnPesqVara.text")); // NOI18N
        btnPesqVara.setName("btnPesqVara"); // NOI18N
        btnPesqVara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqVaraActionPerformed(evt);
            }
        });

        jTabbedPane2.setName("jTabbedPane2"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel3.border.title"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtHistorico.setColumns(20);
        txtHistorico.setRows(5);
        txtHistorico.setName("txtHistorico"); // NOI18N
        jScrollPane1.setViewportView(txtHistorico);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        cbBaixa.setText(resourceMap.getString("cbBaixa.text")); // NOI18N
        cbBaixa.setName("cbBaixa"); // NOI18N
        cbBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBaixaActionPerformed(evt);
            }
        });

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        txtDataCadastro.setName("txtDataCadastro"); // NOI18N

        txtDataProvidencia.setName("txtDataProvidencia"); // NOI18N

        txtDataBaixa.setName("txtDataBaixa"); // NOI18N

        txtHoraProvidencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        txtHoraProvidencia.setName("txtHoraProvidencia"); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel5.border.title"))); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        txtObservacao.setName("txtObservacao"); // NOI18N
        jScrollPane3.setViewportView(txtObservacao);

        jPanel5.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel6.border.title"))); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N

        cbAcompanhamentoTipo.setName("cbAcompanhamentoTipo"); // NOI18N
        cbAcompanhamentoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAcompanhamentoTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbAcompanhamentoTipo, 0, 300, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(cbAcompanhamentoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel7.border.title"))); // NOI18N
        jPanel7.setName("jPanel7"); // NOI18N

        cbAudienciaTipo.setName("cbAudienciaTipo"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbAudienciaTipo, 0, 300, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbAudienciaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel5)
                                .addGap(2, 2, 2)
                                .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataProvidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbBaixa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8))
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHoraProvidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDataBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataProvidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoraProvidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbBaixa)
                            .addComponent(jLabel8)
                            .addComponent(txtDataBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );

        jPanel7.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel7.AccessibleContext.accessibleName")); // NOI18N

        jTabbedPane2.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jtbAcordoParcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parcela", "Vencimento", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbAcordoParcelas.setName("jtbAcordoParcelas"); // NOI18N
        jtbAcordoParcelas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbAcordoParcelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbAcordoParcelasMouseClicked(evt);
            }
        });
        jtbAcordoParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbAcordoParcelasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtbAcordoParcelas);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        txtParcelaValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtParcelaValor.setName("txtParcelaValor"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        txtVencimento.setName("txtVencimento"); // NOI18N

        btnIncluirParcela.setText(resourceMap.getString("btnIncluirParcela.text")); // NOI18N
        btnIncluirParcela.setName("btnIncluirParcela"); // NOI18N
        btnIncluirParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirParcelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtParcelaValor)
                        .addComponent(txtVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnIncluirParcela))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtParcelaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncluirParcela))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab(resourceMap.getString("jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        btnMudarProcesso.setAction(actionMap.get("OutroProcesso")); // NOI18N
        btnMudarProcesso.setName("btnMudarProcesso"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addGap(49, 49, 49)
                .addComponent(btnMudarProcesso)
                .addGap(237, 237, 237))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lNumProcesso)
                    .addComponent(lCodigo))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumeroProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lVara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdVara, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVaraNome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesqVara)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCodigo)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumProcesso)
                    .addComponent(txtNumeroProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lVara)
                    .addComponent(txtIdVara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVaraNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesqVara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnMudarProcesso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NumericDocument gdId = new NumericDocument();
        gdId.setMaxLenght(12);
        txtId.setDocument(gdId);
        new GetsDocument().setMaxLenght(20, txtNumeroProcesso);
        NumericDocument gdIdVara = new NumericDocument();
        gdIdVara.setMaxLenght(6);
        txtIdVara.setDocument(gdIdVara);
        jTabbedPane2.getAccessibleContext().setAccessibleName(resourceMap.getString("jTabbedPane2.AccessibleContext.accessibleName")); // NOI18N

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-852)/2, (screenSize.height-653)/2, 852, 653);
    }// </editor-fold>//GEN-END:initComponents

private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
    if (!txtId.getText().equalsIgnoreCase("")) {
        ProcessoCarregar();
    }
}//GEN-LAST:event_txtIdFocusLost

    @SuppressWarnings("static-access")
private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
}//GEN-LAST:event_txtIdKeyTyped

private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_F10) {
        Pesquisar();
    }
}//GEN-LAST:event_txtIdKeyPressed

private void txtIdVaraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdVaraFocusLost
    VaraCarrega();
    if ((txtIdVara.getText().length() > 0) && (txtNumeroProcesso.getText().length() > 0)) {
        ProcessoCarregar();
    }
}//GEN-LAST:event_txtIdVaraFocusLost

private void txtIdAdvogadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdAdvogadoFocusLost
    AdvogadoCarrega();
}//GEN-LAST:event_txtIdAdvogadoFocusLost

private void txtIdClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdClienteFocusLost
    ClienteCarrega();
}//GEN-LAST:event_txtIdClienteFocusLost

private void txtIdContrariaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdContrariaFocusLost
    ContrariaCarrega();
}//GEN-LAST:event_txtIdContrariaFocusLost

private void btnPesqVaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqVaraActionPerformed
    PesquisarVara();

    if ((txtIdVara.getText().length() > 0) && (txtNumeroProcesso.getText().length() > 0)) {
        ProcessoCarregar();
    }
}//GEN-LAST:event_btnPesqVaraActionPerformed

private void txtNumeroProcessoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroProcessoFocusLost
    if ((txtIdVara.getText().length() > 0) && (txtNumeroProcesso.getText().length() > 0)) {
        ProcessoCarregar();
    }
}//GEN-LAST:event_txtNumeroProcessoFocusLost

private void cbAcompanhamentoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAcompanhamentoTipoActionPerformed
    cbAcompanhamentoTipoModificacoes();
}//GEN-LAST:event_cbAcompanhamentoTipoActionPerformed

private void cbBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBaixaActionPerformed
    txtDataBaixa.setEnabled(cbBaixa.isSelected());
    if (cbBaixa.isEnabled()) {
        txtDataBaixa.setDate(new Date());
    } else {
        txtDataBaixa.setDate(null);
    }
}//GEN-LAST:event_cbBaixaActionPerformed

private void jtbAndamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbAndamentosMouseClicked
    if (evt.getClickCount() > 1) {
        Alterar((Acompanhamento) jtbAndamentos.getValueAt(jtbAndamentos.getSelectedRow(), 5));
    }
}//GEN-LAST:event_jtbAndamentosMouseClicked

private void btnIncluirParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirParcelaActionPerformed
    if ((acompanhamento.getParcela() != null) && (!acompanhamento.getParcela().equalsIgnoreCase(""))) {
        JOptionPane.showMessageDialog(this, "Acompanhamento Vindo de Conversão, não pode ser alterado.");
        return;
    }
    if (txtParcelaValor.getText().length() <= 0) {
        JOptionPane.showMessageDialog(this, "Informe o Valor da Parcela");
        txtParcelaValor.requestFocus();
        return;
    }
    if (txtVencimento.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Informe o Vencimento");
        txtVencimento.requestFocus();
        return;
    }
    AcordoParcela acordoParcela = new AcordoParcela();
    acordoParcela.setVencimento(txtVencimento.getDate());
    try {
        Double parcelaValor = Double.valueOf(formataParcela.parse(txtParcelaValor.getText()).doubleValue());
        acordoParcela.setParcelaValor(parcelaValor);
    } catch (ParseException ex) {
        Logger.getLogger(CadastroAndamentoProcesso.class.getName()).log(Level.SEVERE, null, ex);
    }
    acordoParcela.setAcompanhamento(acompanhamento);
//    acordoParcela.setParcelaValor(Double.valueOf(txtParcelaValor.getText()));

    //if (acompanhamento.getAcordoParcelas().size() == 0) {
    //    acordoParcela.setParcela("1/1");
    //    acompanhamento.getAcordoParcelas().add(acordoParcela);
    //}else{

    if (acordoParcelas.contains(acordoParcela)) {
        JOptionPane.showMessageDialog(this, "Vencimento já está lançado.");
        txtVencimento.requestFocus();
        return;
    }

    Set<AcordoParcela> listaNova = new LinkedHashSet<AcordoParcela>();
    int total = (acordoParcelas.size() + 1);
    int parcela = 1;
    boolean ja = false;
    for (Iterator it = acordoParcelas.iterator(); it.hasNext();) {
        AcordoParcela ver = (AcordoParcela) it.next();
        if (ver.getVencimento().equals(acordoParcela.getVencimento())) {
            JOptionPane.showMessageDialog(this, "Vencimento já está lançado.");
            txtVencimento.requestFocus();
            return;
        }
        if ((ja) || (ver.getVencimento().before(acordoParcela.getVencimento()))) {
            ver.setParcela(parcela++ + "/" + total);
            listaNova.add(ver);
        } else {
            acordoParcela.setParcela(parcela++ + "/" + total);
            listaNova.add(acordoParcela);
            ja = true;

            //ja coloca a proxima
            ver.setParcela(parcela++ + "/" + total);
            listaNova.add(ver);
        }
    }
    if (!ja) {
        acordoParcela.setParcela(parcela++ + "/" + total);
        listaNova.add(acordoParcela);
        ja = true;
    }
    acordoParcelas.clear();
    acordoParcelas.addAll(listaNova);
    //acompanhamento.setAcordoParcelas(listaNova);
    //}
    CarregaParcelas();
}//GEN-LAST:event_btnIncluirParcelaActionPerformed

private void jtbAcordoParcelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbAcordoParcelasKeyPressed
}//GEN-LAST:event_jtbAcordoParcelasKeyPressed

private void jtbAcordoParcelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbAcordoParcelasMouseClicked
    if (evt.getClickCount() > 1) {
        SelecionaParcela();
    }
}//GEN-LAST:event_jtbAcordoParcelasMouseClicked

    public void cbAcompanhamentoTipoModificacoes() {

        AcompanhamentoTipo acompanhamentoTipoSelecionado = ((AcompanhamentoTipo) cbAcompanhamentoTipo.getSelectedItem());

        if (acompanhamentoTipoSelecionado != null) {
            if (acompanhamentoTipoSelecionado.getDescricao().equalsIgnoreCase("Audiência")) {
                cbAudienciaTipo.setEnabled(true);
                cbAudienciaTipo.requestFocus();
            } else {
                cbAudienciaTipo.setSelectedIndex(-1);
                cbAudienciaTipo.setEnabled(false);
            }
            if (acompanhamentoTipoSelecionado.getDescricao().equalsIgnoreCase("Acordo")) {
                jTabbedPane2.setEnabledAt(1, true);
                //jTabbedPane2.setSelectedIndex(1);
            } else {
                jTabbedPane2.setEnabledAt(1, false);
            }
        }
    }
    
    /**
     * Carrega Andamentos
     */
    public void CarregaAndamentos(){
        ResetaAndamentos();
        if (processo == null) return;
        if ((processo.getAcompanhamentos() != null)&&(processo.getAcompanhamentos().size() > 0)){
            DefaultTableModel model = (DefaultTableModel) jtbAndamentos.getModel();
            Object[] aReg = new Object[6];
            for (Iterator it = processo.getAcompanhamentos().iterator(); it.hasNext();) {
                Acompanhamento acompanhamentoRow = (Acompanhamento) it.next();
                aReg[0] = formataDataHora.format(acompanhamentoRow.getDataProximaProvidencia());
                aReg[1] = acompanhamentoRow.getAcompanhamentoTipo();
                if (acompanhamentoRow.getAudienciaTipo() != null){
                    aReg[2] = acompanhamentoRow.getAudienciaTipo();
                }else{
                    aReg[2] = "";
                }
                aReg[3] = formataData.format(acompanhamentoRow.getDataCadastro());
                aReg[4] = acompanhamentoRow.getObservacao();
                aReg[5] = acompanhamentoRow;
                model.addRow(aReg);
            }
        }
    }
    
    /**
     * Reseta tabela andamentos
     */
    public void ResetaAndamentos(){
        DefaultTableModel model = (DefaultTableModel) jtbAndamentos.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    /**
     * Carrega Parcelas
     */
    public void CarregaParcelas() {
        ResetaParcelas();
        if ((acordoParcelas != null)&&(acordoParcelas.size() > 0)){
            DefaultTableModel model = (DefaultTableModel) jtbAcordoParcelas.getModel();
            Object[] aReg = new Object[3];
            for (Iterator it = acordoParcelas.iterator(); it.hasNext();) {
                AcordoParcela acordoParcelaRow = (AcordoParcela) it.next();
                aReg[0] = acordoParcelaRow;
                aReg[1] = formataData.format(acordoParcelaRow.getVencimento());
                aReg[2] = formataParcela.format(acordoParcelaRow.getParcelaValor());
                model.addRow(aReg);
            }
        }
    }
    
    public void SelecionaParcela() {
        if ((acompanhamento.getParcela() != null) && (!acompanhamento.getParcela().equalsIgnoreCase(""))) {
            JOptionPane.showMessageDialog(this, "Acompanhamento Vindo de Conversão, não pode ser alterado.");
            return;
        }
        AcordoParcela removida = (AcordoParcela) jtbAcordoParcelas.getValueAt(jtbAcordoParcelas.getSelectedRow(), 0);
        txtParcelaValor.setText(formataParcela.format(removida.getParcelaValor()));
        txtVencimento.setDate(removida.getVencimento());
        
        acordoParcelas.remove(removida);
        
        Set<AcordoParcela> listaNova = new LinkedHashSet<AcordoParcela>();
        int total = (acordoParcelas.size()+1);
        int parcela = 1;
        for (Iterator it = acordoParcelas.iterator(); it.hasNext();) {
            AcordoParcela ver = (AcordoParcela) it.next();
                ver.setParcela(parcela++ +"/"+total);
                listaNova.add(ver);
        }
        acordoParcelas.clear();
        acordoParcelas.addAll(listaNova);

        
        CarregaParcelas();
    }

    /**
     * Reseta tabela parcelas
     */
    public void ResetaParcelas() {
        DefaultTableModel model = (DefaultTableModel) jtbAcordoParcelas.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }
    
    /**
     * Reinicia formulário
     */
  	public void ResetaForm() {
		txtId.setText("");
        txtAdvogadoContraria.setText("");
        txtIdAdvogado.setText("");
        txtIdCliente.setText("");
        txtIdContraria.setText("");
        txtIdVara.setText("");
        txtNomeAdvogado.setText("");
        txtNomeCliente.setText("");
        txtNomeContraria.setText("");
        txtNumeroProcesso.setText("");
        txtObservacao.setText("");
        txtVaraNome.setText("");

        vara = null;
//        advogado = null;
        cliente = null;
        contraria = null;

  		txtId.setEnabled(true);
        
        txtIdVara.setEnabled(true);
        btnPesqVara.setEnabled(true);
        txtNumeroProcesso.setEnabled(true);
        btnNovo.setEnabled(false);
		txtId.requestFocus();
        jTabbedPane1.setSelectedIndex(0);
        ResetaFormAcompanhamento();
        ResetaAndamentos();
	}
    public void ResetaFormAcompanhamento(){
        txtDataBaixa.setDate(null);
        txtDataCadastro.setDate(null);
        txtHoraProvidencia.setText("");
        txtDataProvidencia.setDate(null);
        txtHistorico.setText("");
        txtObservacao.setText("");
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        jTabbedPane2.setSelectedIndex(0);
        cbAcompanhamentoTipo.setSelectedIndex(-1);
        cbAudienciaTipo.setSelectedIndex(-1);
        cbAudienciaTipo.setEnabled(false);
        cbBaixa.setEnabled(false);
        FormAcompanhamento(false);
        txtDataBaixa.setEnabled(false);
        //TODO RESSETA TAB ACOMPANHAMENTOS NO PROCESSO
        acordoParcelas.clear();
        cbAcompanhamentoTipoMonta();
        cbAudienciaTipoMonta();
        ResetaFormAcordo();
    }
    
    public void FormAcompanhamento(boolean val){
        cbAcompanhamentoTipo.setEnabled(val);
        txtDataCadastro.setEnabled(val);
        txtDataProvidencia.setEnabled(val);
        txtVencimento.setEnabled(val);
        txtHistorico.setEnabled(val);
        txtHoraProvidencia.setEnabled(val);
        txtObservacao.setEnabled(val);
        cbBaixa.setEnabled(val);
        jTabbedPane2.setEnabled(val);
        jTabbedPane2.setEnabledAt(0,val);        
        
    }
    
    public void ResetaFormAcordo(){
        //TODO ressetar tabela vencimentos
        ResetaFormParcelas();
    }
    public void ResetaFormParcelas(){
        txtParcelaValor.setText("");
        txtVencimento.setDate(null);
        ResetaParcelas();
    }
    
    @Action
    /**
     * Abre tela de pesquisa
     */
    public void Pesquisar(){

        if (pesquisa == null) {
            pesquisa = new PesquisaProcesso(getDaoFactory());
        }
                
        pesquisa.setTitle("Selecione o Processo para Alteração.");
        pesquisa.doSearch();
        pesquisa.openSearch();
        Processo vem = pesquisa.getEntity();
        if (vem != null){
            txtId.setText(String.valueOf(vem.getId()));
            ProcessoCarregar();
        }
    }

    @Action
    /**
     * Abre tela de pesquisa
     */
    public void PesquisarVara(){

        if (pesquisaVara == null) {
            pesquisaVara = new PesquisaVara(getDaoFactory());
        }
                
        pesquisaVara.setTitle("Selecione a Vara.");
        pesquisaVara.doSearch();
        pesquisaVara.openSearch();
        vara = pesquisaVara.getEntity();
        if (vara != null){
            txtIdVara.setText(String.valueOf(vara.getId()));
            VaraCarrega();
        }
    }

    
	@Action
    /**
     * Prepara formulário para novo cadastro
     */
	public void Novo() {
		ResetaFormAcompanhamento();
		//txtId.setEnabled(false);
		acompanhamento = new Acompanhamento();
        acompanhamento.setProcesso(processo);
		acompanhamentoDAO = daoFactory.getAcompanhamentoDAO();
        FormAcompanhamento(true);
        jTabbedPane2.setEnabledAt(1,false);
		btnSalvar.setEnabled(true);
	}

    public void VaraCarrega(){
        if (txtIdVara.getText().length() <= 0) return;
        // Busca nova sessao
		VaraDAO varaDAO = daoFactory.getVaraDAO();
		try {
            // Inicia transação
			t = varaDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            vara = varaDAO.findById(
                    Integer.valueOf(txtIdVara.getText()), false);
            
            // Preenche dados no formulário
            txtVaraNome.setText(vara.getNome());

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("vara.errobusca", txtIdVara.getText()));
		}        
    }

    public void AdvogadoCarrega(){
        if (txtIdAdvogado.getText().length() <= 0) return;
        // Busca nova sessao
		AdvogadoDAO advogadoDAO = daoFactory.getAdvogadoDAO();
		try {
            // Inicia transação
			t = advogadoDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            advogado = advogadoDAO.findById(
                    Long.valueOf(txtIdAdvogado.getText()), false);
            
            // Preenche dados no formulário
            txtNomeAdvogado.setText(advogado.getNome());

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("advogado.errobusca", txtIdAdvogado.getText()));
		}        
    }

    public void ClienteCarrega() {
        if (txtIdCliente.getText().length() <= 0) return;
        // Busca nova sessao
       	PessoaDAO pessoaDAO = daoFactory.getPessoaDAO();
		try {
            // Inicia transação
			t = pessoaDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            cliente = pessoaDAO.findById(
                    Long.valueOf(txtIdCliente.getText()), false);
            
            // Preenche dados no formulário
            txtNomeCliente.setText(cliente.getNome());

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("pessoa.errobusca", txtIdCliente.getText()));
		}        
    }
    
    public void ContrariaCarrega() {
        if (txtIdContraria.getText().length() <= 0) return;
        // Busca nova sessao
        PessoaDAO pessoaDAO = daoFactory.getPessoaDAO();
        try {
            // Inicia transação
			t = pessoaDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            contraria = pessoaDAO.findById(
                    Long.valueOf(txtIdContraria.getText()), false);
            
            // Preenche dados no formulário
            txtNomeContraria.setText(contraria.getNome());

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("pessoa.errobusca", txtIdContraria.getText()));
		}        
    }
    
	@Action
    /**
     * Salva novo cadastro ou altera
     */
	public void Salvar() {

        AcompanhamentoTipo acompanhamentoTipo = (AcompanhamentoTipo) cbAcompanhamentoTipo.getSelectedItem();
        if (acompanhamentoTipo == null){
            	JOptionPane.showMessageDialog(this, "Selecione um tipo de andamento");
                cbAcompanhamentoTipo.requestFocus();
                return;
        }else{
            if (acompanhamentoTipo.getDescricao().equalsIgnoreCase("Audiência")){
                AudienciaTipo audienciaTipo = (AudienciaTipo) cbAudienciaTipo.getSelectedItem();
               if (audienciaTipo == null) {
                   JOptionPane.showMessageDialog(this, "Selecione um tipo de audiência");
                   cbAudienciaTipo.requestFocus();
                   return;
               }
            }
        }
        if (txtDataProvidencia.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma data para providência");
            txtDataProvidencia.requestFocus();
            return;
        }
        
        // se id for nulo trata como inclusão
		if (acompanhamento.getId() == null) {

            if (!Seguranca.Permitido("Processos-Acompanhamentos-inclusao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }

            
            //acompanhamento = new Acompanhamento();
			t = acompanhamentoDAO.getSession().beginTransaction();
			t.begin();
			try {

                
                
				// Preenche dado nos objetos
                acompanhamento.setAcompanhamentoTipo(acompanhamentoTipo);
                acompanhamento.setAudienciaTipo((AudienciaTipo) cbAudienciaTipo.getSelectedItem());
                acompanhamento.setBaixa(cbBaixa.isSelected());
                if ((cbBaixa.isSelected())&&(txtDataBaixa.getDate() == null)){
                    txtDataBaixa.setDate(new Date());
                }
                acompanhamento.setDataBaixa(txtDataBaixa.getDate());
                //TODO HORABAIXA
                /*
                if (txtHoraBaixa.getText().length() == 5) {
                    acompanhamento.getDataBaixa().setHours(Integer.parseInt(txtHoraBaixa.getText().substring(0, 2)));
                    acompanhamento.getDataBaixa().setMinutes(Integer.parseInt(txtHoraBaixa.getText().substring(3, 5)));
                }
                 */
                if (txtDataCadastro.getDate() == null){
                    txtDataCadastro.setDate(new Date());
                }
                acompanhamento.setDataCadastro(txtDataCadastro.getDate());
                
                acompanhamento.setDataProximaProvidencia(txtDataProvidencia.getDate());
                if (txtHoraProvidencia.getText().length() == 5) {
                    acompanhamento.getDataProximaProvidencia().setHours(Integer.parseInt(txtHoraProvidencia.getText().substring(0, 2)));
                    acompanhamento.getDataProximaProvidencia().setMinutes(Integer.parseInt(txtHoraProvidencia.getText().substring(3, 5)));
                }
                acompanhamento.setHistorico(txtHistorico.getText());
                acompanhamento.setObservacao(txtObservacao.getText());

                
                // Grava 
				acompanhamentoDAO.makePersistent(acompanhamento);
				t.commit();
               
                
                AcordoParcelaDAO acordoParcelaDAO = daoFactory.getAcordoParcelaDAO();
                t = acordoParcelaDAO.getSession().getTransaction();
                t.begin();
                //Object[] aDireitos = lmDireitos.toArray();
                //for (int i = 0; i < aDireitos.length; i++) {
                 //   UsuarioDireito direito = (UsuarioDireito)aDireitos[i];
                  //  direito.setUsuario(usuario);
                  //  usuarioDireitoDAO.makePersistent(direito);
                //}
                for (Iterator<AcordoParcela> it = acordoParcelas.iterator(); it.hasNext();) {
                    AcordoParcela acordoParcela = it.next();
                    acordoParcela.setAcompanhamento(acompanhamento);
                    acordoParcelaDAO.makePersistent(acordoParcela);
                }
                t.commit();
                
                
                // Confirma
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.sucesso", 
						String.valueOf(acompanhamento.getId())));
                // Reseta
                acompanhamento = null;
                processo = null;
                ResetaFormAcompanhamento();
                ProcessoCarregar();
                jTabbedPane1.setSelectedIndex(1);
			} catch (Exception e) {
                // Se ocorre algum erro, mostra mensagem e desfaz transação
                e.printStackTrace();
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.erro") +
					e.getLocalizedMessage());
				t.rollback();
			}


		// Se for alteração
		} else {
            
            if (!Seguranca.Permitido("Processos-Acompanhamentos-alteracao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }

            
            try {
                
                if ((acompanhamento.getParcela()!=null)&&(!acompanhamento.getParcela().equalsIgnoreCase(""))){
                 	JOptionPane.showMessageDialog(this, "Acompanhamento Vindo de Conversão, não pode ser alterado.");
                    return;               
                }

                // Preenche dado nos objetos
                acompanhamento.setAcompanhamentoTipo((AcompanhamentoTipo) cbAcompanhamentoTipo.getSelectedItem());
                acompanhamento.setAudienciaTipo((AudienciaTipo) cbAudienciaTipo.getSelectedItem());
                acompanhamento.setBaixa(cbBaixa.isSelected());
                if ((cbBaixa.isSelected())&&(txtDataBaixa.getDate() == null)){
                    txtDataBaixa.setDate(new Date());
                }
                acompanhamento.setDataBaixa(txtDataBaixa.getDate());
                if (txtDataCadastro.getDate() == null){
                    txtDataCadastro.setDate(new Date());
                }
                acompanhamento.setDataCadastro(txtDataCadastro.getDate());
                
                acompanhamento.setDataProximaProvidencia(txtDataProvidencia.getDate());
                if (txtHoraProvidencia.getText().length() == 5) {
                    acompanhamento.getDataProximaProvidencia().setHours(Integer.parseInt(txtHoraProvidencia.getText().substring(0, 2)));
                    acompanhamento.getDataProximaProvidencia().setMinutes(Integer.parseInt(txtHoraProvidencia.getText().substring(3, 5)));
                }                
                acompanhamento.setHistorico(txtHistorico.getText());
                acompanhamento.setObservacao(txtObservacao.getText());
                
                
                acompanhamento.setAcordoParcelas(acordoParcelas);
                
                // Grava alterações
				acompanhamentoDAO.makePersistent(acompanhamento);
				t.commit();
                
                
                AcordoParcelaDAO acordoParcelaDAO = daoFactory.getAcordoParcelaDAO();
                t = acordoParcelaDAO.getSession().getTransaction();
                t.begin();
                for (Iterator<AcordoParcela> it = acordoParcelas.iterator(); it.hasNext();) {
                    AcordoParcela acordoParcela = it.next();
                    acordoParcela.setAcompanhamento(acompanhamento);
                    acordoParcelaDAO.makePersistent(acordoParcela);
                }
                t.commit();
                
                // Mostra confirmação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.sucesso"));
                
                // Reinicia formulario
                acompanhamento = null;
                processo = null;
                ResetaFormAcompanhamento();
                ProcessoCarregar();
                jTabbedPane1.setSelectedIndex(1);

			} catch (Exception e) {
                // Qualquer erro mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.erro") +
                        e.getLocalizedMessage());
				t.rollback();
			}
		}
	}

    /**
     * Abre cadastro no formulário para alteração
     */
	public void ProcessoCarregar() {
        // Busca nova sessao
		processoDAO = daoFactory.getProcessoDAO();
		try {
            // Inicia transação
			t = processoDAO.getSession().beginTransaction();
            
            if (txtId.getText().length() > 0){
            // Busca objeto pelo id informado
            processo = processoDAO.findById(
                    Long.valueOf(txtId.getText()), false);
                txtIdVara.setText(processo.getVara().getId().toString());
                txtVaraNome.setText(processo.getVara().getNome());
                txtNumeroProcesso.setText(processo.getNumeroProcesso());
            }else{
                processo = processoDAO.buscaPorNumeroProcessoVara(txtNumeroProcesso.getText(), vara);
            }
            
            
            
            
            // Preenche dados no formulário
            txtAdvogadoContraria.setText(processo.getAdvogadoContraria());
            txtIdAdvogado.setText(processo.getAdvogado().getId().toString());
            AdvogadoCarrega();
            
            if (processo.getAutor()){

            cliente = processo.getReclamante();
            contraria = processo.getReclamado();
            }else{

            cliente = processo.getReclamado();
            contraria = processo.getReclamante();                
            }
            txtIdCliente.setText(cliente.getId().toString());
            txtIdContraria.setText(contraria.getId().toString());
            txtNomeCliente.setText(cliente.getNome());
            txtNomeContraria.setText(contraria.getNome());

            //TODO CARREGA TABELA ACOMPANHAMENTOS
            
            // Ativa controles disponíveis
            txtId.setEnabled(false);
            txtIdVara.setEnabled(false);
            btnPesqVara.setEnabled(false);
            btnNovo.setEnabled(true);
            txtNumeroProcesso.setEnabled(false);
            jTabbedPane1.setSelectedIndex(0);
            CarregaAndamentos();

		} catch (Exception e) {
            // Se não acha, nostra mensagem
            e.printStackTrace();
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("processo.errobusca", txtId.getText()));
			txtId.setEnabled(true);
			btnSalvar.setEnabled(false);
			btnNovo.setEnabled(false);
            btnExcluir.setEnabled(false);
			txtId.requestFocus();
		}
	}

    @Action 
    /**
     * Alterar
     */
    public void Alterar(Acompanhamento vem){
        Long id = vem.getId();
        // Busca nova sessao
        acompanhamentoDAO = daoFactory.getAcompanhamentoDAO();
		try {
            ResetaFormAcompanhamento();
            // Inicia transação
			t = acompanhamentoDAO.getSession().beginTransaction();
            
            if (id != null){
            // Busca objeto pelo id informado
            acompanhamento = acompanhamentoDAO.findById(
                    id, true);
            }
            // Preenche dados
            txtDataBaixa.setDate(acompanhamento.getDataBaixa());
            txtDataCadastro.setDate(acompanhamento.getDataCadastro());
            txtDataProvidencia.setDate(acompanhamento.getDataProximaProvidencia());
            
            txtHoraProvidencia.setText(formataHora.format(acompanhamento.getDataProximaProvidencia()));
            txtObservacao.setText(acompanhamento.getObservacao());
            txtHistorico.setText(acompanhamento.getHistorico());
            
            cbAcompanhamentoTipo.setSelectedItem(acompanhamento.getAcompanhamentoTipo());
            //cbAudienciaTipo.setSelectedItem(acompanhamento.getAudienciaTipo());
            cbBaixa.setSelected(acompanhamento.getBaixa());
            
            // Ativa controles disponíveis
            FormAcompanhamento(true);
            if (acompanhamento.getBaixa()){
                txtDataBaixa.setEnabled(true);
            }
            if (acompanhamento.getAudienciaTipo() != null){
                cbAudienciaTipo.setEnabled(true);
                cbAudienciaTipo.setSelectedItem(acompanhamento.getAudienciaTipo());
            }
            if (acompanhamento.getAcompanhamentoTipo().getDescricao().equalsIgnoreCase("Acordo")){
                jTabbedPane2.setEnabledAt(1, true);
            }else{
                jTabbedPane2.setEnabledAt(1, false);
            }
            acordoParcelas.clear();
            acordoParcelas.addAll(acompanhamento.getAcordoParcelas());
            
            if (acordoParcelas!=null) { 
                CarregaParcelas();
            }else {
                ;
            }
			btnSalvar.setEnabled(true);
			btnExcluir.setEnabled(true);
            txtId.setEnabled(false);
            txtIdVara.setEnabled(false);
            btnPesqVara.setEnabled(false);
            txtNumeroProcesso.setEnabled(false);
            jTabbedPane2.setSelectedIndex(0);
            

		} catch (Exception e) {
            // Se não acha, nostra mensagem
            e.printStackTrace();
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("altera.errobusca", txtId.getText()));
			txtId.setEnabled(true);
			btnSalvar.setEnabled(false);
			btnExcluir.setEnabled(false);
			txtId.requestFocus();
		}        
    }
    
	@Action
    /**
     * Limpa formulário, cancelando edição atual
     */
	public void Cancelar() {
		acompanhamento = null;
		ResetaFormAcompanhamento();
	}
    
    @Action
    /**
     * Limpa formulário, cancelando edição atual
     */
	public void OutroProcesso() {
		processo = null;
		ResetaForm();
        CarregaAndamentos();
	}
	
	@Action
    /**
     * Exclui objeto atual
     */
	public void Excluir() {
        
        if (!Seguranca.Permitido("Processos-Acompanhamentos-exclusao")) {
            JOptionPane.showMessageDialog(null, "Sem permissão");
            return;
        }

        
		// Solicita confirmação
        int opcao = JOptionPane.showConfirmDialog(this,
                resourceMap.getString("exclui.confirmacao"),
                resourceMap.getString("exclui.confirmacao.titulo"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        switch (opcao) {
			case 0: // Resposta sim
				try {
                    // Remove da persistencia
					acompanhamentoDAO.makeTransient(acompanhamento);
					t.commit();
                    // Confirma
					JOptionPane.showMessageDialog(this,
						resourceMap.getString("exclui.ok"));
                    // Limpa form
					acompanhamento = null;
                    processo = null;
					ResetaFormAcompanhamento();
                    ProcessoCarregar();
                    jTabbedPane1.setSelectedIndex(1);

				} catch (Exception e) {
                    // Dando erro diz que não é possivel
                    e.printStackTrace();
					JOptionPane.showMessageDialog(this,
						resourceMap.getString(
						"exclui.naopode"));
				}
				break;
			case 1: // Resposta não
				break;
		}

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alerta;
    private javax.swing.ButtonGroup bgTipoAndamento;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluirParcela;
    private javax.swing.JButton btnMudarProcesso;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesqVara;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbAcompanhamentoTipo;
    private javax.swing.JComboBox cbAudienciaTipo;
    private javax.swing.JCheckBox cbBaixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpDetalhes;
    private javax.swing.JTable jtbAcordoParcelas;
    private javax.swing.JTable jtbAndamentos;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lNumProcesso;
    private javax.swing.JLabel lVara;
    private javax.swing.JTextField txtAdvogadoContraria;
    private org.jdesktop.swingx.JXDatePicker txtDataBaixa;
    private org.jdesktop.swingx.JXDatePicker txtDataCadastro;
    private org.jdesktop.swingx.JXDatePicker txtDataProvidencia;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JFormattedTextField txtHoraProvidencia;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JTextField txtIdAdvogado;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdContraria;
    private javax.swing.JTextField txtIdVara;
    private javax.swing.JTextField txtNomeAdvogado;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeContraria;
    private javax.swing.JFormattedTextField txtNumeroProcesso;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JFormattedTextField txtParcelaValor;
    private javax.swing.JTextField txtVaraNome;
    private org.jdesktop.swingx.JXDatePicker txtVencimento;
    // End of variables declaration//GEN-END:variables

	public SchedulaDAOFactory getDaoFactory() {
		return daoFactory;
	}

	public void setDaoFactory(SchedulaDAOFactory daoFactory) {
		this.daoFactory = daoFactory;
	}

    private void cbAcompanhamentoTipoMonta() {
        cbAcompanhamentoTipo.removeAllItems();
        AcompanhamentoTipoDAO acompanhamentoTipoDAO =  getDaoFactory().getAcompanhamentoTipoDAO();
        Transaction tcbm = acompanhamentoTipoDAO.getSession().getTransaction();
        tcbm.begin();
        List<AcompanhamentoTipo> list = acompanhamentoTipoDAO.findAll();
        Iterator<AcompanhamentoTipo> it = list.iterator();
        while (it.hasNext()) {
            cbAcompanhamentoTipo.addItem(it.next());
        }
    }
    
    private void cbAudienciaTipoMonta() {
        cbAudienciaTipo.removeAllItems();
        AudienciaTipoDAO audienciaTipoDAO =  getDaoFactory().getAudienciaTipoDAO();
        Transaction tcbm = audienciaTipoDAO.getSession().getTransaction();
        tcbm.begin();
        List<AudienciaTipo> list = audienciaTipoDAO.findAll();
        Iterator<AudienciaTipo> it = list.iterator();
        while (it.hasNext()) {
            cbAudienciaTipo.addItem(it.next());
        }
    }    
}
