/*
 * CadastroEstadoCivil.java
 *
 * Created on May 27, 2008, 9:09 PM
 */
package br.com.perettis.schedula;

import br.com.perettis.gets.swing.NumericDocument;
import br.com.perettis.gets.swing.GetsDocument;
import br.com.perettis.schedula.entity.Comarca;
import br.com.perettis.schedula.model.ComarcaDAO;
import br.com.perettis.schedula.model.SchedulaDAOFactory;
import br.com.perettis.schedula.model.Seguranca;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import org.hibernate.Transaction;
import org.jdesktop.application.Action;

/**
 *
 * @author  Vinicius Peretti
 * 
 * 
 */
public class CadastroComarca extends javax.swing.JFrame {

    Comarca comarca;
    ComarcaDAO comarcaDAO;
    private SchedulaDAOFactory daoFactory;
    Transaction t;
    org.jdesktop.application.ResourceMap resourceMap;
    PesquisaComarca pesquisa;

    /** Creates new form CadastroEstadoCivil */
    public CadastroComarca(SchedulaDAOFactory daoFactory) {
        setDaoFactory(daoFactory);
        initComponents();
        ResetaForm();
        resourceMap = org.jdesktop.application.Application.getInstance(
                br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroComarca.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alerta = new javax.swing.JOptionPane();
        lCodigo = new javax.swing.JLabel();
        lDescricao = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbDesabilitado = new javax.swing.JCheckBox();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtId = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JFormattedTextField();

        alerta.setName("alerta"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(CadastroComarca.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImage(new Imagens().getIcone());
        setName("Form"); // NOI18N

        lCodigo.setText(resourceMap.getString("lCodigo.text")); // NOI18N
        lCodigo.setName("lCodigo"); // NOI18N

        lDescricao.setText(resourceMap.getString("lDescricao.text")); // NOI18N
        lDescricao.setName("lDescricao"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getActionMap(CadastroComarca.class, this);
        btnNovo.setAction(actionMap.get("Novo")); // NOI18N
        btnNovo.setText(resourceMap.getString("btnNovo.text")); // NOI18N
        btnNovo.setName("btnNovo"); // NOI18N

        btnSalvar.setAction(actionMap.get("Salvar")); // NOI18N
        btnSalvar.setText(resourceMap.getString("btnSalvar.text")); // NOI18N
        btnSalvar.setName("btnSalvar"); // NOI18N

        btnCancelar.setAction(actionMap.get("Cancelar")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        cbDesabilitado.setText(resourceMap.getString("cbDesabilitado.text")); // NOI18N
        cbDesabilitado.setName("cbDesabilitado"); // NOI18N

        btnExcluir.setAction(actionMap.get("Excluir")); // NOI18N
        btnExcluir.setText(resourceMap.getString("btnExcluir.text")); // NOI18N
        btnExcluir.setName("btnExcluir"); // NOI18N

        btnPesquisar.setAction(actionMap.get("Pesquisar")); // NOI18N
        btnPesquisar.setText(resourceMap.getString("btnPesquisar.text")); // NOI18N
        btnPesquisar.setName("btnPesquisar"); // NOI18N

        txtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId.setToolTipText(resourceMap.getString("txtId.toolTipText")); // NOI18N
        txtId.setName("txtId"); // NOI18N
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        txtNome.setText(resourceMap.getString("txtNome.text")); // NOI18N
        txtNome.setName("txtNome"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lDescricao)
                    .addComponent(lCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDesabilitado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCodigo)
                    .addComponent(btnNovo)
                    .addComponent(btnPesquisar)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDescricao)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(cbDesabilitado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        NumericDocument gdId = new NumericDocument();
        gdId.setMaxLenght(6);
        txtId.setDocument(gdId);
        new GetsDocument().setMaxLenght(50, txtNome);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-412)/2, (screenSize.height-325)/2, 412, 325);
    }// </editor-fold>//GEN-END:initComponents

private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
    if (!txtId.getText().equalsIgnoreCase("")) {
        Alterar();
    }
}//GEN-LAST:event_txtIdFocusLost

    @SuppressWarnings("static-access")
private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
}//GEN-LAST:event_txtIdKeyTyped

private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_F10) {
        Pesquisar();
    }
}//GEN-LAST:event_txtIdKeyPressed

    
    /**
     * Reinicia formulário
     */
  	public void ResetaForm() {
		txtId.setText("");
		txtNome.setText("");
		cbDesabilitado.setSelected(false);
		txtId.setEnabled(true);
		txtId.requestFocus();
		btnSalvar.setEnabled(false);
		btnExcluir.setEnabled(false);
	}
    
    @Action
    /**
     * Abre tela de pesquisa
     */
    public void Pesquisar(){
        if (pesquisa == null) {
            pesquisa = new PesquisaComarca(getDaoFactory());
        }
        
        pesquisa.setTitle("Selecione a Comarca para Alteração.");
        pesquisa.doSearch();
        pesquisa.openSearch();
        Comarca vem = pesquisa.getEntity();
        if (vem != null){
            txtId.setText(String.valueOf(vem.getId()));
            Alterar();
        }
    }

	@Action
    /**
     * Prepara formulário para novo cadastro
     */
	public void Novo() {
		ResetaForm();
		txtId.setEnabled(false);
		comarca = new Comarca();
		comarcaDAO = daoFactory.getComarcaDAO();
		btnSalvar.setEnabled(true);
	}

	@Action
    /**
     * Salva novo cadastro ou altera
     */
	public void Salvar() {

        // se id for nulo trata como inclusão
		if (comarca.getId() == null) {    
         
            if (!Seguranca.Permitido("Parametros-CadastroComarca-inclusao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }
            
            comarca = new Comarca();
			t = comarcaDAO.getSession().beginTransaction();
			t.begin();
			try {
                //Verifica se já existe mesma descrição
				if (comarcaDAO.buscaPorNome(txtNome.getText())
						!= null) {
					JOptionPane.showMessageDialog(
						this,
						resourceMap.getString("jaexiste.nome", 
							String.valueOf(txtNome.getText())));
					txtNome.requestFocus();
					return;
				}

				// Preenche dado nos objetos
				comarca.setNome(txtNome.getText());
				comarca.setDesabilitado(cbDesabilitado.isSelected());
                
                // Grava 
				comarcaDAO.makePersistent(comarca);
				t.commit();
                
                // Confirma
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.sucesso", 
						String.valueOf(comarca.getId())));
                // Reseta
                comarca = null;
                ResetaForm();
			} catch (Exception e) {
                // Se ocorre algum erro, mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.erro") +
					e.getLocalizedMessage());
				t.rollback();
			}


		// Se for alteração
		} else {
         
            if (!Seguranca.Permitido("Parametros-CadastroComarca-alteracao")) {
                JOptionPane.showMessageDialog(null, "Sem permissão");
                return;
            }
            
            try {
                // Verifica se existe outro com mesmos dados
                Comarca outro = comarcaDAO.buscaPorNome(
                        txtNome.getText());
                if (outro != null) {
                    if (outro.getId() != comarca.getId()) {

                        JOptionPane.showMessageDialog(this,
                                resourceMap.getString("jaexiste.nome",
                                String.valueOf(txtNome.getText())));
                        txtNome.requestFocus();
                        return;
                    }
                }

				// Preenche dados do form no objeto
				comarca.setNome(txtNome.getText());
				comarca.setDesabilitado(cbDesabilitado.isSelected());
                
                // Grava alterações
				comarcaDAO.makePersistent(comarca);
				t.commit();
                
                // Mostra confirmação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.sucesso"));
                
                // Reinicia formulario
                comarca = null;
				ResetaForm();

			} catch (Exception e) {
                // Qualquer erro mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.erro") +
                        e.getLocalizedMessage());
				t.rollback();
			}
		}
	}

    /**
     * Abre cadastro no formulário para alteração
     */
	public void Alterar() {
        // Busca nova sessao
		comarcaDAO = daoFactory.getComarcaDAO();
		try {
            // Inicia transação
			t = comarcaDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            comarca = comarcaDAO.findById(
                    Integer.valueOf(txtId.getText()), true);
            
            // Preenche dados no formulário
            txtNome.setText(comarca.getNome());
            cbDesabilitado.setSelected(comarca.isDesabilitado());
            
            // Ativa controles disponíveis
			btnSalvar.setEnabled(true);
			btnExcluir.setEnabled(true);
            txtId.setEnabled(false);

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("altera.errobusca", txtId.getText()));
			txtId.setEnabled(true);
			btnSalvar.setEnabled(false);
			btnExcluir.setEnabled(false);
			txtId.requestFocus();
		}
	}

	@Action
    /**
     * Limpa formulário, cancelando edição atual
     */
	public void Cancelar() {
		comarca = null;
		ResetaForm();
	}
	
	@Action
    /**
     * Exclui objeto atual
     */
	public void Excluir() {
        
        if (!Seguranca.Permitido("Parametros-CadastroComarca-exclusao")) {
            JOptionPane.showMessageDialog(null, "Sem permissão");
            return;
        }
        
		// Solicita confirmação
        int opcao = JOptionPane.showConfirmDialog(this,
                resourceMap.getString("exclui.confirmacao"),
                resourceMap.getString("exclui.confirmacao.titulo"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        switch (opcao) {
			case 0: // Resposta sim
				try {
                    // Remove da persistencia
					comarcaDAO.makeTransient(comarca);
					t.commit();
                    // Confirma
					JOptionPane.showMessageDialog(this,
						resourceMap.getString("exclui.ok"));
                    // Limpa form
					comarca = null;
					ResetaForm();

				} catch (Exception e) {
                    // Dando erro diz que não é possivel
					JOptionPane.showMessageDialog(this,
						resourceMap.getString(
						"exclui.naopode"));
				}
				break;
			case 1: // Resposta não
				break;
		}

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alerta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox cbDesabilitado;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lDescricao;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JFormattedTextField txtNome;
    // End of variables declaration//GEN-END:variables

	public SchedulaDAOFactory getDaoFactory() {
		return daoFactory;
	}

	public void setDaoFactory(SchedulaDAOFactory daoFactory) {
		this.daoFactory = daoFactory;
	}

}
