/*
 * doAdtb.java
 *
 * Created on 29 de Junho de 2008, 22:24
 */

package br.com.perettis.schedula;

import br.com.perettis.schedula.entity.Comarca;
import br.com.perettis.schedula.entity.Vara;
import br.com.perettis.schedula.model.ComarcaDAO;
import br.com.perettis.schedula.model.SchedulaDAOFactory;
import br.com.perettis.schedula.model.VaraDAO;
import br.com.perettis.schedula.versoes.doAdtb_Advogados;
import br.com.perettis.schedula.versoes.doAdtb_Processos;
import br.com.perettis.schedula.versoes.doAdtb_Requerentes;
import br.com.perettis.schedula.versoes.doAdtb_Requeridos;
import javax.swing.DefaultListModel;
import org.hibernate.Transaction;

/**
 *
 * @author  vinicius
 */
public class doAdtb extends javax.swing.JFrame {

    DefaultListModel lmStatus = new DefaultListModel();
    private SchedulaDAOFactory daoFactory;
    /** Creates new form doAdtb */
    public doAdtb(SchedulaDAOFactory daoFactory) {
        setDaoFactory(daoFactory);
        initComponents();
        jlStatus.setModel(lmStatus);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlStatus = new javax.swing.JList();
        btnIniciar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(br.com.perettis.schedula.SchedulaApp.class).getContext().getResourceMap(doAdtb.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jlStatus.setName("jlStatus"); // NOI18N
        jScrollPane1.setViewportView(jlStatus);

        btnIniciar.setText(resourceMap.getString("btnIniciar.text")); // NOI18N
        btnIniciar.setName("btnIniciar"); // NOI18N
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIniciar))
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnIniciar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
    executa();
}//GEN-LAST:event_btnIniciarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new doAdtb().setVisible(true);
            }
        });
    }

    
    public void executa(){
        Transaction t;


        ComarcaDAO comarcaDAO = daoFactory.getComarcaDAO();
        t = comarcaDAO.getSession().getTransaction();
        t.begin();
        Comarca comarca = new Comarca();
        comarca.setNome("Campo Grande/MS");
        comarcaDAO.makePersistent(comarca);
        t.commit();
        
        
        VaraDAO varaDAO = daoFactory.getVaraDAO();
        String[][] aVaras = {
        {"1a. Vara Trabalhista"},
        {"2a. Vara Trabalhista"},
        {"3a. Vara Trabalhista"},
        {"4a. Vara Trabalhista"},
        {"5a. Vara Trabalhista"},
        {"6a. Vara Trabalhista"},
        {"7a. Vara Trabalhista"},
        {"1a. Vara Civil (antiga vara 8)"},
        {"2a. Vara Civil (antiga vara 9)"},
        {"3a. Vara Civil (antiga vara 0)"}
        };
        t = varaDAO.getSession().getTransaction();
        t.begin();
        for (int i = 0; i < aVaras.length; i++) {
        String[] aVara = aVaras[i];
        Vara vara = new Vara();
        vara.setNome(aVara[0]);
        vara.setComarca(comarca);
        varaDAO.makePersistent(vara);
        }
        t.commit();
        
        
        lmStatus.addElement("Carregando Advogados");
        doAdtb_Advogados doAdvogados = new doAdtb_Advogados(getDaoFactory());
        doAdvogados.executa();
        lmStatus.addElement(doAdvogados.getConta()+ " Advogados importados");
        
        lmStatus.addElement("Carregando Reclamantes");
        doAdtb_Requerentes doRequerentes = new doAdtb_Requerentes(getDaoFactory());
        doRequerentes.executa();
        lmStatus.addElement(doRequerentes.getConta()+ " Reclamantes importados");
        
        lmStatus.addElement("Carregando Reclamados");
        doAdtb_Requeridos doRequeridos = new doAdtb_Requeridos(getDaoFactory());
        doRequeridos.executa();
        lmStatus.addElement(doRequeridos.getConta()+ " Reclamados importados");

        //if (true) return;
        
        lmStatus.addElement("Carregando Processos");
        doAdtb_Processos doProcessos = new doAdtb_Processos(getDaoFactory());
        doProcessos.executa();
        lmStatus.addElement(doProcessos.getConta()+ " Processos importados");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jlStatus;
    // End of variables declaration//GEN-END:variables

    public SchedulaDAOFactory getDaoFactory() {
        return daoFactory;
    }

    public void setDaoFactory(SchedulaDAOFactory daoFactory) {
        this.daoFactory = daoFactory;
    }

}
